-- ══════════════════════════════════════════════════════════════════
-- Importación de notificaciones de incidentes pendientes
-- Hospital Santa Margarita · SGC ISO 9001:2015
--
-- Origen: "Formulario de Notificación de Incidentes de la Atención
-- Clínica (Respuestas)" — 137 respuestas acumuladas, de las cuales
-- 15 nunca llegaron a la tabla clinical_incidents.
--
-- Faltantes por mes -> 2026-05: 5, 2026-06: 10
--
-- Es SEGURO ejecutarlo más de una vez: cada renglón solo se inserta
-- si no existe ya una notificación del mismo paciente en la misma
-- fecha (WHERE NOT EXISTS al final).
--
-- Ejecutar en: Supabase → SQL Editor
-- ══════════════════════════════════════════════════════════════════

BEGIN;

WITH nuevos (patient_name, patient_dob, patient_sex, incident_date, incident_time, location, incident_type, incident_subtype, damage_level, description, causes, contributing_factors, mitigating_factors, immediate_actions, attachments, reported_at) AS (
  VALUES
    ('GUTIERREZ GONZALEZ,  MAURICIO', '1971-02-07', 'Masculino', '2026-05-20', '5:00:00 a.m.', 'Hospitalización', 'Evento Adverso', 'Medicación / Fluidos IV (Ej: dosis incorrecta, omisión)', 'Sin Daño', 'PACIENTE MASCULINO QUE INGRESA POR IAM SEST, SE LE REALIZA CATETERISMO CARDIACO EL DIA DE AYER, A LAS 5AM APROXIMADAMENTE REPORTA ENFERMERIA QUE SE LE ADMINISTRO LA SOLUCION A CHORRO., TENIA UNA SOL. SALINA 500CC PARA 24HRS.
PACIENTE NO REFIERE NINGUNA SINTOMATOLOGIA, SE LE INFORMA A MEDICO TRATANTE Y SOLICITA YA NO SE LE COLOQUE OTRA SOLUCION Y SE DESCANALICE PORQUE SE VA DE ALTA. 
SIGNOS VITALES 23HRS: TA 132/67, FC 80, FR 18, TEMP 37, SAT 91
SIGNOS VITALES 5HRS: TA 108/76, FC 82, FR 18, TEMP 36.8, SAT 92
SIGNOS VITALES 8HRS: TA 112/79, FC 88, FR 18, TEMP 37.6, SAT 93', 'ESTE TIPO DE SITUACIONES SON CAUSADAS POR LA FALTA DE VIGILANCIA DE ENFERMERIA.', 'Protocolos inadecuados o inexistentes, Formación o supervisión inadecuadas', 'Intervención oportuna de otro personal', 'SE LE INFORMA A MEDICO TRATANTE', 'https://drive.google.com/open?id=1ZgLHwPFtIesHGm6ag0WXYKBgaKmg7FbE', '2026-05-20 09:06:41'),
    ('GANDARILLA PEREZ,  JACQUELINE', '2005-11-22', 'Femenino', '2026-05-22', '10:25:00 a.m.', 'Hospitalización', 'Evento Adverso', 'Documentación / Comunicación', 'Sin Daño', 'Medicos de guardia da la indicacion via telefonica a enfermeria de que se retire la sonda foley y que en un momento mas se acude a colocar el sello ya que se encuentra dandole atencion medica a otro paciente hospitalizado. 
Supervisora de enfermeria del turno matutino Raquel, le niega el permiso de acatar dicha indicacion a la enfermera encargada y cuando medico de guardia acude a piso es cuando se le informa que no se le retiro la sonda foley por indicacion de la supervisora. 
Medico de guardia le vuelve a dar la indicacion a la enfermera de que si se debe retirar esa sonda foley porque ya se habia dado la indicacion via telefonica y se coloca sello de que fue  indicacion dada por medica tratante. 
Supervisora Raquel acude a tachar el sello, "corrigiendo" la hora en la que se dio la indicacion, discutiendo que es la hora de la segunda indicacion, no de la primera vez que se dio la indicacion. 
Lo cual es incorrecto porque se dio una indicacion y no se acato porque lo decidio, no porque fuera indicacion medica. Tuvo que volverse a dar la indicacion por su accion.', 'El que la supervisora Raquel haya negado el permiso de acatar la indicacion, retrasa la evolucion favorable de la paciente para que deambulara y se bañara en regadera.
Agregando que se habia hecho una capacitacion donde nos comentaron que no debian existir tachones en indicaciones, ella como maestra corrigiendo a un alumno coloca una X en la hora de la indicacion. 
Dichas acciones quitan autoridad, ponen en duda las indicaciones de los medicos y demuestra que no respeta los labores de medicos de guardia, confrontando altaneramente a medicos de guardia.', 'Formación o supervisión inadecuadas', 'Intervención oportuna de otro personal', 'Se le solicita a la enfermera encargada que inmediatamente se retire sonda foley.', 'https://drive.google.com/open?id=1vvEvhlvnZfJ-bx4wVACWUl_GvabU2mg8', '2026-05-22 14:51:02'),
    ('Guillermina Cuevas Lugo', '1931-01-01', 'Femenino', '2026-05-26', '9:17:00 a.m.', 'Hospitalización', 'Cuasi Falla', 'Comportamiento del Paciente', 'Sin Daño', 'El paciente no podia moverse y para su trasladó de rx a planta baja117 se pido silla de ruedas el familiar del paciente pidio mover al paciente en peso muerto, quise ofrecer otras opciones pero el familiar tomo la iniciativa y cargo a su familiar en peso muerto, el inconveniente fue al servicio siguiente cuando me piden mover al paciente yo pregunto si hay una indicacion para moverlo y mo lastimarlo el familiar del paciente se lo tomo mal y me comento que era mi responsabilidad saberlo opte por hacer mi trabajo mover al paciente y disculparme por que el familiar del paciente estaba muy hermético y no me dejo explicar el porque de mi pregunta', 'Pedir mal el equipo nde inmovilización en vez de silla era una camilla', 'Condición clínica compleja del paciente, Comunicación deficiente en el equipo', 'El paciente o familiar alertó del error', 'Hacer el reporte oportuno', NULL, '2026-05-27 07:51:04'),
    ('María Elena Garcia Roman', '1961-09-11', 'Femenino', '2026-05-28', '8:00:00 a.m.', 'Hospitalización', 'Evento Adverso', 'Medicación / Fluidos IV (Ej: dosis incorrecta, omisión)', 'Sin Daño', 'Enfermera a cargo administró concentración erronea de albumina humana, se te tenía imdicada al 25% y la administró al 20%', 'No leer bien sus indicaciones', 'Fatiga / Sobrecarga de trabajo del personal', 'Intervención oportuna de otro personal', 'Retroalimentación al personal de enfermería', NULL, '2026-05-31 12:17:23'),
    ('Juan Carlos Camarena Lopez', '1969-09-01', 'Masculino', '2026-05-31', '7:30:00 p.m.', 'Hospitalización', 'Cuasi Falla', 'Caídas', 'Leve', 'Paciente en procedimiento después de entubación y aspiración de secreciones, se me pide camilla para el egreso del ya mencionado el cual, al momento de ingresar con camilla encuentro a el paciente en el piso después de escuchar un golpe fuerte al haber salido de la sala, médico tratante no hace mención de nada, ni indica medidas que tomar posterior de la caída, se hace inspección de paciente y niega tener alguna molestia pero se observa anisocoricas.', 'No conozco la causa, ni doctor tratante ni anestesió me hacen mención de nada', 'Condición clínica compleja del paciente', 'Intervención oportuna de otro personal', 'Se mantiene en monitoreo continuo al paciente', NULL, '2026-05-31 20:18:14'),
    ('Ochoa Oyosa Abigail', '1994-09-15', 'Femenino', '2026-06-04', '4:38:00 p.m.', 'Hospitalización', 'Evento Adverso', 'Documentación / Comunicación', 'Sin Daño', 'Se hace registro con datos incorrectos de paciente, se registra como OCHOA AYOSA ABIGAIL, el nombre correcto es OCHOA OYOSA ABIGAIL, no se realiza una correcta idetificación de paciente, se hace omisión de Acciones Escenciales, se ve involucrado concentimientos de quirofano, hojas de efermería, notas medicas.', 'Mala comunicación, no se realiza correctamente la identifiacion correta de paciente', 'Barreras de comunicación (idioma, cognición)', 'Intervención oportuna de otro personal', 'Retroaliemntación a personal', NULL, '2026-06-04 14:05:38'),
    ('GONZALEZ TELLEZ, MANUEL', '1953-11-18', 'Masculino', '2026-06-05', '8:15:00 a.m.', 'Hospitalización', 'Cuasi Falla', 'Documentación / Comunicación', 'Sin Daño', 'Error en el nombre del paciente. 
Nombre del paciente: GONZALEZ TELLEZ, MANUEL
Error del nombre en laboratorio: MANUEL GONZALEZ TELLOZ', 'Falta de atención', 'Protocolos inadecuados o inexistentes, Formación o supervisión inadecuadas', 'Intervención oportuna de otro personal, Doble chequeo por parte del personal', 'Se notifica a laboratorio', 'https://drive.google.com/open?id=1h7mjr5GCKQUxY0BcIrlhaH0zRpUM6cQ2', '2026-06-05 10:01:18'),
    ('MARTIN PEDROZA, SALVADOR', '1950-04-13', 'Masculino', '2026-06-08', '10:00:00 a.m.', 'Hospitalización', 'Cuasi Falla', 'Comportamiento del Paciente', 'Leve', 'PACIENTE QUE SE REHUSA AL TRATAMIENTO, LO QUE IMPOSIBILITA UNA MEJORA DEL PADECIMIENTO. CON MAL TRATO AL PERSONAL EN GENERAL, DESDE ENFERMERÍA, MEDICOS DE GUARDIA Y MÉDICO TRATANTE, LEVANTANDO LA VOZ, SIENDO ALTANERO Y MENOSPRECIANDO. COMENTA QUE EL DIAGNOSTICO ES ERRONEO A PESAR DE ESTUDIOS DE LABORATORIO E IMAGEN QUE ORIENTAN A MISMO DIAGNOSTICO (BLOQUEO DE RAMA DERECHA+ANGINA DE PECHO INESTABLE). SOLICITA ALTA VOLUNTARIA Y NIEGA DIAGNOSTICOS PREVIAMENTE DADOS DURANTE INTERROGATORIO PARA REALIZAR HISTORIA CLÍNICA.', 'INCONFORMIDAD', 'Condición clínica compleja del paciente', 'Uso de una lista de verificación (checklist)', 'SE INFORMA A MEDICO TRATANTE DE NEGATIVA DEL PACIENTE, ASÍ COMO SU DECISIÓN DE ALTA VOLUNTARIA.', NULL, '2026-06-08 13:45:47'),
    ('Elvira Urzua Álvarez', '1939-07-01', 'Femenino', '2026-06-11', '7:42:00 p.m.', 'Hospitalización', 'Evento Adverso', 'Documentación / Comunicación', 'Sin Daño', 'A la revisión de expedientes se identifica sello de comunicación telefónica mal redactado con tachaduras ,espacios incompletos con indicaciones poco clara y con vía de administración incorrecta', 'Mala redacción en sello de comunicación efectiva', 'Barreras de comunicación (idioma, cognición), Comunicación deficiente en el equipo, Protocolos inadecuados o inexistentes', 'Doble chequeo por parte del personal', '.', NULL, '2026-06-12 09:46:43'),
    ('URZUA ALVARES, ELVIRA', '1939-07-01', 'Femenino', '2026-06-12', '9:47:00 a.m.', 'Hospitalización', 'Cuasi Falla', 'Comportamiento del Paciente', 'Sin Daño', 'DESDE EL DIA DE AYER HIJO REPORTA DESATENCION DE MEDICOS DE GUARDIA, ENFERMERIA Y MEDICOS TRATANTES, CUANDO TODO EL PERSONAL HA ACUDIDO A CADA LLAMADO QUE HA SOLICITADO EN MULTIPLES OCASIONES.
EL DIA DE HOY EXPRESA QUE EL ES MUY EXIGENTE Y SU MAMA REQUIERE TODA LA ATENCION NECESARIA Y QUE EL ESTA PAGANDO UN SERVICIO Y QUIERE UN ENFERMERO Y UN MEDICO DE GUARDIA DE BASE CON SU MAMÁ TODO EL TIEMPO. APARTE RECLAMA QUE SUS MEDICOS TRATANTES NO LE CONTESTAN EL TELEFONO. 
SIN ENTENDER QUE SE TIENEN MAS PACIENTES A NUESTRO CARGO', 'HIJO APRENSIVO Y GROSERO, CUIDADORA SOLICITA LAS COSAS DE MALA MANERA.', 'Condición clínica compleja del paciente', 'Intervención oportuna de otro personal', 'SE LE EXPLICA QUE NO ES POSIBLE LA ATENCION EXCLUSIVA Y QUE NO SOMOS RESPONSABLES DE LA ATENCION DE SUS MEDICOS TRATANTES.', NULL, '2026-06-12 09:53:07'),
    ('MEDINA PESTAÑO, HECTOR SERVANDO', '1960-11-27', 'Masculino', '2026-06-13', '3:16:00 p.m.', 'Urgencias', 'Cuasi Falla', 'Documentación / Comunicación', 'Leve', 'PACIENTE MASCULINO INGRESADO POR URGENCIAS, QUE EN SUS DOCUMENTOS DE INGRESO SE LE PONE DE SEXO FEMENINO POR PARTE DEL SERVICIO DE ADMISIÓN, LO QUE PONE EN DUDA RESTO DE INFORMACIÓN DE INGRESO.', 'MALA CAPACITACIÓN POR PARTE DE SU JEFATURA, ASÍ COMO CONSTANTE DISTRACCIÓN ANTE SITUACIONES DE IMPORTANCIA.
ESTA NO ES LA PRIMERA VEZ QUE SUCEDE UN ERROR DE ESTE TIPO, INCLUSO POR PARTE DE MISMA JEFATURA DE ADMISIÓN CUANDO SE ENCUENTRA SUPLIENDO A ALGUNA COMPAÑER@.
EN REPETIDAS OCASIONES SIN ANUNCIAR INGRESOS, LO QUE RETRASA LA ATENCIÓN HACIA EL PACIENTE.', 'Comunicación deficiente en el equipo, Protocolos inadecuados o inexistentes, Personal insuficiente, Formación o supervisión inadecuadas', 'Intervención oportuna de otro personal', 'SE SOLICITA AL AREA DE ADMISIÓN LA CORRECCIÓN DE DOCUMENTOS.', 'https://drive.google.com/open?id=11CtO5f9FQufWhnhQYB9seqhrXt2WR-Rp, https://drive.google.com/open?id=1CIx_yligZgpPiZ5CI0ckFt3DFKa7XfP2, https://drive.google.com/open?id=1tMgGrfg2CaVXJtKebkralKUCfJNEDAfg', '2026-06-13 18:30:52'),
    ('RAMIREZ MOLINA, PABLA', '1957-06-03', 'Masculino', '2026-06-15', '3:00:00 p.m.', 'Hospitalización', 'Cuasi Falla', 'Medicación / Fluidos IV (Ej: dosis incorrecta, omisión)', 'Sin Daño', 'PACIENTE FEMENINA CON QUE INGRESA A NUESTRO NOSOCOMIO Y POR HIPOTENSION SE LE DECIDE INICIAR NOREPINEFRINA EN EL SERVICIO DE URGENCIAS, PASA A PISO Y TRATANTE MENCIONA NO QUERER MONITOR, REFIERE QUE A EL NO LE PIDIERON AUTORIZACION PARA INICIAR LA NOREPINEFRINA EN URGENCIAS. 
SE LE VUELVE A CUESTIONAR A MEDICO TRATANTE  SI QUIERE MONITOR POR LAS AMINAS Y SE NIEGA.
EL DIA 15/06/26 A LAS 13:00HRS ENFERMERIA SOLICITA UN SELLO DE INDICACION TELEFONICA DONDE SE PONGA QUE PACIENTE ESTARA SIN MONITOR, EL CUAL NO SE COLOCA PORQUE NO TENEMOS UN PROTOCOLO HOSPITALARIO DONDE OBLIGA A LOS MEDICOS A TENER A SUS PACIENTES CON AMINAS CON MONITOR CARDIACO. 
MEDICO SOLICITA SE COMIENCE A DESTETAR AMINAS, ENTREGANDO GUARDIA MATUTINA CON NOREPINEFRINA A 1.5ML/HR, ENFERMERIA DE TURNO VESPERTINO TOMA SIGNOS VITALES Y POR HIPOTENSION NO REPORTADA EN HOJA DE ENFERMERIA LE SUBE SIN AVISAR AMINAS A 3ML/HR Y LE COLOCA MONITOR SIN TENER AUTORIZACION. SIGNOS DE LAS 16:00HRS TA 100/70 
MEDICO TRATANTE SOLICITA RETIRAR MONITOR Y SUSPENDER LA NOREPINEFRINA, SE LE EXPLICA QUE ENFERMERIA LA AUMENTO Y TENEMOS QUE VOLVER A DESTETAR, ACUDE A PASAR VISITA NUEVAMENTE Y SOLICITA RETIRAR MONITOR Y ENFERMERIA SE NIEGA, POR LO CUAL DEJA INDICADO A LAS 19:00HRS "DESCARTAR NOREPINEFRINA .5ML CADA 2HRS HASTA SUSPENDER INDEPENDIENTE DE TOMA DE TENSION ARTERIAL MANUAL, AL SUSPENDER NOREPINEFRINA DESCARTAR MONITOR CARDIACO", NOREPINEFRINA A 2.5ML/HR
TURNO NOCTURNO RECIBE NOREPINEFRINA A 2ML/HR, ENFERMERIA NO SIGUE DICHA INDICACION Y EN LUGAR DE CONTINUAR DESTETANDO NOREPINEFRINA VOLVIERON A AUMENTARLA A 4ML/HR, SE LES LLAMO LA ATENCION Y REFIRIERON QUE IBAN A SEGUIR INDICACIONES.
ES EL DIA 16/06/26 A LAS 8:24 HRS Y LA PACIENTE CONTINUA CON MONITOR CARDIACO Y CON NOREPINEFRINA A 1ML/HR POR DESTETE INADECUADO.  A LAS 5:00HRS TA 68/98, PACIENTE ASINTOMATICA.', 'USO INADECUADO DE SUMINISTROS MEDICOS, INADECUADO CONTROL DE TENSION ARTERIAL', 'Fatiga / Sobrecarga de trabajo del personal, Comunicación deficiente en el equipo, Personal insuficiente, Formación o supervisión inadecuadas', 'Intervención oportuna de otro personal', 'DOCTOR ACUDE A DAR DE ALTA A LA PACIENTE', 'https://drive.google.com/open?id=1ivO8OfQ3TVcv1cJQ35SJNPpCx5698fre, https://drive.google.com/open?id=1FKKdFd2zGS7jZsgcsOCt9lxlcyz1OTTr, https://drive.google.com/open?id=1AeLUsjJbwkCAtc-_2nbAg5_firxh-nHR', '2026-06-16 08:42:53'),
    ('TORRES BALCAZAR, TOMAS', '1937-12-21', 'Masculino', '2026-06-19', '1:00:00 p.m.', 'Hospitalización', 'Cuasi Falla', 'Sangre / Productos Sanguíneos', 'Sin Daño', 'Medico tratante solicita laboratoriales a las 9:57 hrs, se coloca sello a las 10:02hrs, a las 11:20hrs se acude a revisar si estaban resultados de laboratorio y aun no estaban, se revisa indicaciones y ya estaba firmado por laboratorio dando a entender que si se tomaron, a las 12:40hrs aun sin resultados de laboratorio se acude a cuestionar por los resultados obteniendo por respuesta que no tomaron la muestra porque leyeron en las indicas CVC (cateter venoso central) cuando en realidad era EVC (evento cerebrovascular)', 'falta de atencion de parte del personal y no corroborar con enfermeria.', 'Fatiga / Sobrecarga de trabajo del personal, Comunicación deficiente en el equipo, Personal insuficiente', 'Intervención oportuna de otro personal', 'se solicita tomen de inmediato los laboratoriales, ya que medico tratante ya estaba solicitandolos', 'https://drive.google.com/open?id=1dqbte8j-I23LK3MkI8nnFuoTJiUTIihf, https://drive.google.com/open?id=1fRbWJ-hn54z1ay8uX05iBi0fC4FYeQ4z', '2026-06-22 15:51:07'),
    ('CERDA MORONES NOEMY ALEJANDRA', '1989-06-23', 'Femenino', '2026-06-19', '4:00:00 p.m.', 'Hospitalización', 'Cuasi Falla', 'Sangre / Productos Sanguíneos', 'Sin Daño', 'MEDICA TRATANTE SOLICITA LABORATORIALES A LAS 16:08HRS, SE COLOCA EL SELLO A LAS 16:15HRS, MEDICA TRATANTE SOLICITA LOS RESULTADOS A LAS 17:55HRS Y AL REVISAR SISTEMA Y EXPEDIENTE SIN RESULTADOS AUN (ESE DIA CON CODIGO MAGENTA POR LO CUAL SE ASOCIO AL RETRAZO), MEDICA TRATANTE SE COMUNICA DIRECTO A LABORATORIO DONDE LE REFIEREN QUE NUNCA SE SOLICITO UNA BH Y EXPRESA SU MOLESTIA.', 'FALTA DE COMUNICACION ENTRE DEPARTAMENTOS, NO REVISION ADECUADA DE INDICACIONES', 'Comunicación deficiente en el equipo', 'Intervención oportuna de otro personal', 'SE SOLICITA TOMEN LA BH INDICADA', 'https://drive.google.com/open?id=1M1ASsw1JR77Xz9cFFN6aNy4rTjSVDVHX, https://drive.google.com/open?id=1pW-ddErG6iOaj6bhjBKK_XGfg_HNNvkD', '2026-06-22 15:59:34'),
    ('Mora Vazquez Laurentina', '1947-12-28', 'Femenino', '2026-06-19', '8:00:00 p.m.', 'Hospitalización', 'Evento Adverso', 'Medicación / Fluidos IV (Ej: dosis incorrecta, omisión)', 'Sin Daño', 'se administra Acido Acetil Salicilisco en lugar de acetilcisteina', 'mala lectura a la indicaciones medicas por lo tanta se administra erroneamento tratamiento', 'Barreras de comunicación (idioma, cognición), Comunicación deficiente en el equipo', 'Intervención oportuna de otro personal', 'Se informa a medico tratante y se realiza vigilancia estrecha', NULL, '2026-06-22 18:11:14')
)
INSERT INTO public.clinical_incidents (patient_name, patient_dob, patient_sex, incident_date, incident_time, location, incident_type, incident_subtype, damage_level, description, causes, contributing_factors, mitigating_factors, immediate_actions, attachments, reported_at)
SELECT n.patient_name, n.patient_dob::date, n.patient_sex, n.incident_date::date, n.incident_time, n.location, n.incident_type, n.incident_subtype, n.damage_level, n.description, n.causes, n.contributing_factors, n.mitigating_factors, n.immediate_actions, n.attachments, n.reported_at::timestamptz
FROM nuevos n
WHERE NOT EXISTS (
  SELECT 1 FROM public.clinical_incidents c
  WHERE c.incident_date = n.incident_date::date
    AND upper(btrim(c.patient_name)) = upper(btrim(n.patient_name))
);

COMMIT;

-- ── Verificación ──────────────────────────────────────────────────
-- Debe quedar: total 137, mayo 2026 = 11, junio 2026 = 10
SELECT count(*) AS total_notificaciones FROM public.clinical_incidents;

SELECT to_char(incident_date, 'YYYY-MM') AS mes, count(*) AS notificaciones
FROM public.clinical_incidents
WHERE incident_date >= '2026-01-01'
GROUP BY 1 ORDER BY 1;

SELECT incident_type, count(*) AS n
FROM public.clinical_incidents
WHERE incident_date BETWEEN '2026-06-01' AND '2026-06-30'
GROUP BY 1 ORDER BY 2 DESC;
