-- ══════════════════════════════════════════════════════════════════
-- Catálogo de medicamentos para el Perfil Farmacoterapéutico (PFT)
-- Hospital Santa Margarita · Cuadro básico 2026
--
-- Carga los medicamentos de Analgesia, Antibióticos e Infusiones (soluciones
-- intravenosas) al catálogo maestro, etiquetados por categoría. En el PFT,
-- cada bloque (Infusiones / Antibióticos / Analgesia) sugiere su categoría
-- al capturar (el buscador sigue permitiendo escribir cualquier otro).
--
-- Re-ejecutable: no duplica; si un medicamento ya existía, solo le pone
-- o actualiza su categoría. No borra nada.
--
-- Ejecutar en: Supabase → SQL Editor
-- ══════════════════════════════════════════════════════════════════

-- Columna de categoría (si aún no existe)
ALTER TABLE public.pharmacy_med_catalog ADD COLUMN IF NOT EXISTS categoria TEXT;

INSERT INTO public.pharmacy_med_catalog (nombre, atc, alto_riesgo, activo, categoria) VALUES
  ('ASPIRINA (ACIDO ACETILSALICILICO) 500mg TABLETAS CJA C/40', 'N', false, true, 'analgesia'),
  ('ASPIRINA EFERVESCENTE (ACIDO ACETILSALICILICO) 500mg TABLETAS EFERVESCENTES CJA', 'N', false, true, 'analgesia'),
  ('GI CELECOXIB 200mg CAPSULAS C/10 (ULTRA)', 'N', false, true, 'analgesia'),
  ('DORIXINA (CLONIXINATO DE LISINA) 125mg TAB CJA C/10 (SIEGFRED)', 'N', false, true, 'analgesia'),
  ('GI CLONIXINATO DE LISINA 100mg/2ml SOL INY AMP (AMSA)', 'N', false, true, 'analgesia'),
  ('STADIUM (DEXKETOPROFENO) 25mg TABLETAS CJA C/10 (SANFER)', 'N', false, true, 'analgesia'),
  ('STADIUM (DEXKETOPROFENO) 50mg/2ml SOLUCION INYECTABLE', 'N', false, true, 'analgesia'),
  ('KERAL (DEXKETOPROFENO) 50mg/2ml SOL INY AMP (MENARINI)', 'N', false, true, 'analgesia'),
  ('VELIAN (DEXKETOPROFENO) 25mg/10ml SOBRES CAJA CON 10', 'N', false, true, 'analgesia'),
  ('VOLTAREN EMULGEL (DICLOFENACO) 1.16% GEL TUBO C/100g (HALEON)', 'N', false, true, 'analgesia'),
  ('ARCOXIA (ETORICOXIB) 120mg COMPRIMIDOS CJA C/7 (MSD)', 'N', false, true, 'analgesia'),
  ('MOTRIN PEDIATRICO (IBUPROFENO) 40mg/1ml GOTAS SUSPENSION FCO C/15ml', 'N', false, true, 'analgesia'),
  ('GI DOLVER (IBUPROFENO) 200mg TABLETAS C/20', 'N', false, true, 'analgesia'),
  ('GELUBRIN (IBUPROFENO) 400mg CAPSULAS CJA C/10', 'N', false, true, 'analgesia'),
  ('GI DOLVER (IBUPROFENO) 600mg TABLETAS C/20 (MAVER)', 'N', false, true, 'analgesia'),
  ('INDAFLEX (INDOMETACINA) 2.5% CREMA TUBO C/40g', 'N', false, true, 'analgesia'),
  ('INDOCID (INDOMETACINA) 100mg SUPOSITORIOS CJA C/15 (ASPEN)', 'N', false, true, 'analgesia'),
  ('TRALIKEN (KETOPROFENO) 100mg SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('SUPRADOL (KETOROLACO) 30mg SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('SUPRADOL (KETOROLACO) 60mg SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('SUPRADOL (KETOROLACO) 30mg TABLETAS SUBLINGUALES C/4', 'N', false, true, 'analgesia'),
  ('SUPRADOL (KETOROLACO) 10mg TABLETAS C/10', 'N', false, true, 'analgesia'),
  ('DOLAC (KETOROLACO) 30mg SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('GI KETOROLACO 30mg TABLETA SUBLINGUAL C/6 (AMSA)', 'N', false, true, 'analgesia'),
  ('TREVINAL (KETOROLACO) 30mg/ml SOLUCION INYECTABLE AMPULA (VITALIS)', 'N', false, true, 'analgesia'),
  ('ONEMER (KETOROLACO) 30mg SOL INY AMPULA (PISA)', 'N', false, true, 'analgesia'),
  ('EXEL (MELOXICAM) 7.5mg TABLETAS CAJA CON 20 TABLETAS', 'N', false, true, 'analgesia'),
  ('GI MAVICAM (MELOXICAM) 15mg TAB C/10 (MAVI/SAFER)', 'N', false, true, 'analgesia'),
  ('PIXIBA (PARECOXIB) 40mg SOLUCION INYECTABLE (PISA)', 'N', false, true, 'analgesia'),
  ('BIOFER (PARACETAMOL) 500mg TAB CJA C/10', 'N', false, true, 'analgesia'),
  ('GI PARACETAMOL 750mg TABLETAS C/10 (AVIVIA)', 'N', false, true, 'analgesia'),
  ('TAFIROL AC (PARACETAMOL/DICLOFENACO) 500mg/50mg TAB CJA C/15 (ASOFARMA)', 'N', false, true, 'analgesia'),
  ('PERFALGAN (PARACETAMOL) 500mg/50ml SOL INY FCO (ASPEN)', 'N', false, true, 'analgesia'),
  ('TAFIROL (PARACETAMOL) 1g TABLETAS CJA C/20', 'N', false, true, 'analgesia'),
  ('NUCLEO CMP FORTE (CITIDIN-5-MONOFOSFATO/URIDIN-5TRIFOSFATO) 5mg/3mg CAP CJA C/30', 'N', false, true, 'analgesia'),
  ('VARTALON COMPOSITUM (GLUCOSAMINA/CONDROITINA) 1500mg/1200mg GRANULADO CJA C/30 S', 'N', false, true, 'analgesia'),
  ('NOVOVARTALON (GLUCOSAMINA/MELOXICAM) 1500mg/15mg SOBRES CAJA CON 30 SOBRES', 'N', false, true, 'analgesia'),
  ('PIASCLEDINE 300 (PERSEA GRASTISSIMA/GLYCINE MAX) 100mg/200mg CAPSULAS CJA C/30', 'N', false, true, 'analgesia'),
  ('BROSPINA (BUPRENORFINA) 0.3mg/ml SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('SOLORO 7 (BUPRENORFINA) 10mg PARCHE CJA C/2 PARCHES (GRUNENTHAL)', 'N', false, true, 'analgesia'),
  ('SOLORO 7 (BUPRENORFINA) 5mg PARCHE CJA C/2 PARCHES', 'N', false, true, 'analgesia'),
  ('DORIXINA-TMR (CLONIXINATO DE LISINA/TRAMADOL) 125mg/25mg TABLETAS CAJA C/14', 'N', false, true, 'analgesia'),
  ('GI MAVIDOL TR (KETOROLACO/TRAMADOL) 10mg/25mg CAPSULAS C/10', 'N', false, true, 'analgesia'),
  ('SUPRADOL DUET (KETOROLACO/TRAMADOL) 10mg/25mg SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('ONEMER DT (KETOROLACO/TRAMADOL) 10mg/25mg /1mL  AMPULA (PISA)', 'N', false, true, 'analgesia'),
  ('GRATEN (MORFINA) 10mg/10ml SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('GRATEN (MORFINA) 2.5mg/2.5ml SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('BUFIGEN (NALBUFINA) 10mg/1ml SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('TRADOL (TRAMADOL) 100mg/2ml SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('TRADOL (TRAMADOL) 50mg SOL INYECTABLE AMP 1mL (GRUNENTHAL)', 'N', false, true, 'analgesia'),
  ('GI TRAMADOL 100mg/ml SOLUCION ORAL GOTAS FRASCO C/10ml (AMSA)', 'N', false, true, 'analgesia'),
  ('SKUDEXA (TRAMADOL/DEXKETOPROFENO) 75mg/25mg TABLETAS CJA C/10', 'N', false, true, 'analgesia'),
  ('GI TRAMADOL/PARACETAMOL 37.5mg/325mg TABLETAS CJA C/20 (AMSA)', 'N', false, true, 'analgesia'),
  ('ALNEX (METAMIZOL SODICO) 1g/2ml SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('GI PIRINOVAG (METAMIZOL SODICO) 500mg TABLETAS C/10 TABLETAS', 'N', false, true, 'analgesia'),
  ('GI CARISOPRODOL/DICLOFENACO 200mg/50mg TABLETAS  CAJA CON 20 TABLETAS (RAYERE)', 'N', false, true, 'analgesia'),
  ('DORIXINA RELAX (CLONIXINATO DE LISINA/CICLOBENZAPRINA) 125mg/5mg TAB CJA C/20 (S', 'N', false, true, 'analgesia'),
  ('NEUROFLAX (COBAMAMIDA/TIOCOLCHICOSIDO) 20mg/4mg SOLUCION INYECTABLE AMPULA', 'N', false, true, 'analgesia'),
  ('DORSAL (MELOXICAM/CARISOPRODOL) 15mg/200mg TAB CJA C/7 (SILANES)', 'N', false, true, 'analgesia'),
  ('FLEXIVER COMPUESTO (MELOXICAM/METOCARBAMOL) 15mg/215mg CAPSULAS CJA C/20', 'N', false, true, 'analgesia'),
  ('DOLOCAM-PLUS (MELOXICAM/METOCARBAMOL) 15mg/215mg CAPSULAS CJA C/10', 'N', false, true, 'analgesia'),
  ('OFELICON (MELOXICAM/METOCARBAMOL) 15mg/215mg CAPSULAS CJA C/10', 'N', false, true, 'analgesia'),
  ('CARIDOXEN (NAPROXENO/CARISOPRODOL) 250mg/200mg CAPSULAS CAJA CON 30 CAPSULAS', 'N', false, true, 'analgesia'),
  ('TAFIROL FLEX (PARACETAMOL/CLORZOXAZONA) 300mg/250mg TABLETAS CJA C/30', 'N', false, true, 'analgesia'),
  ('NORFLEX PLUS (PARACETAMOL/ORFENADRINA) 450mg/35mg CAPSULAS CJA C/50', 'N', false, true, 'analgesia'),
  ('EQUALTHA ANIDULAFUNGINA SOL FCO 100mg (PFIZER)', 'J', false, true, 'antibioticos'),
  ('GI AMIKACINA 500mg/2ml SOL INY AMP (AMSA)', 'J', false, true, 'antibioticos'),
  ('TRAZIDEX OFTENO (DEXAMETASONA/TOBRAMICINA) 1mg/3mg 5mL SUSP OFTALMICA (SOPHIA)', 'J', false, true, 'antibioticos'),
  ('GI GENTAMICINA 160mg/2ml SOL INY AMP (AMSA)', 'J', false, true, 'antibioticos'),
  ('GI GENKOVA (GENTAMICINA) 80mg/2ml SOL INY AMP', 'J', false, true, 'antibioticos'),
  ('GI GENKOVA (GENTAMICINA) 160mg/2ml SOL INY AMP', 'J', false, true, 'antibioticos'),
  ('GI GENTAMICINA 80mg/2ml SOL INY AMP (AMSA)', 'J', false, true, 'antibioticos'),
  ('CLORAMFENI OFTENO (CLORANFENICOL) 5mg/ml 15mL SOL OFTALMICA (LAB SOPHIA)', 'J', false, true, 'antibioticos'),
  ('CLORAMFENI UNGENA (CLORANFENICOL) 0.5% POMADA TUBO CON 5g', 'J', false, true, 'antibioticos'),
  ('FENICOL (CLORANFENICOL) 5mg/ml SOL OFT FCO GOT C/10ml', 'J', false, true, 'antibioticos'),
  ('GI CLORANFENICOL 5mg/ml SOL OFT FCO GOT C/15ml (AMSA)', 'J', false, true, 'antibioticos'),
  ('ACELER-CO (ACIDO FUSIDICO/BETAMETASONA ) 2% - 0.1% CREMA TUBO C/15g CUTANEA (ITR', 'J', false, true, 'antibioticos'),
  ('GI MUPIROCINA 2% UNGUENTO TUBO 15g (PHARMALIFE)', 'J', false, true, 'antibioticos'),
  ('ARGENTAFIL (SULFADIAZINA DE PLATA) 1% CREMA TUBO CON 160g', 'J', false, true, 'antibioticos'),
  ('FURACIN (NITROFURAL) 0.2g POMADA TUBO CON 85g', 'J', false, true, 'antibioticos'),
  ('GI AMOXICILINA 500mg CAPSULAS C/12 (AMSA)', 'J', false, true, 'antibioticos'),
  ('CLAMOXIN (AMOXICILINA/ACIDO CLAVULANICO) 500mg/125mg TABLETAS FRASCO CON 10 TABL', 'J', false, true, 'antibioticos'),
  ('GI CLAMOXIN 12 H (AMOXICILINA/ACIDO CLAVULANICO) 875mg/125mg TABLETA C/10', 'J', false, true, 'antibioticos'),
  ('AMPICILINA 1g/5mL SOLUCION INYECTABLE AMPULA (AMSA)', 'J', false, true, 'antibioticos'),
  ('PENBRITIN (AMPICILINA) 500mg/5mL SUSPENSION ORAL FCO P/100mL (HORMONA LAB)', 'J', false, true, 'antibioticos'),
  ('MEXAPIN (AMPICILINA) 250mg/5mL 60ML SUSP FCO (WANDEL)', 'J', false, true, 'antibioticos'),
  ('PISACILINA (BENCILPENICILINA SODICA) 5''000,000 UI SOL INY AMPULA', 'J', false, true, 'antibioticos'),
  ('POSIPEN (DICLOXACILINA) 500mg TAB CJA C/12 TAB (SANFER)', 'J', false, true, 'antibioticos'),
  ('PIPTABAC (PIPERACILINA/TAZOBACTAM) 4g/0.5g SOLUCION INYECTABLE AMPULA', 'J', false, true, 'antibioticos'),
  ('INVANZ (ERTAPENEM) 1g SOLUCION INYECTABLE AMPULA', 'J', false, true, 'antibioticos'),
  ('FINATAK (ERTAPENEM) 1g SOL INY FCO AMP (KENER)', 'J', false, true, 'antibioticos'),
  ('PRAGMA (ERTAPENEM) 1g SOL INY FCO AMP (PISA) (4053192)', 'J', false, true, 'antibioticos'),
  ('ARZOMEBA (IMIPENEM/CILASTATINA) 500mg/500mg SOL INY FCO (PISA)', 'J', false, true, 'antibioticos'),
  ('PISAPEM (MEROPENEM) 1g SOLUCION INYECTABLE FRASCO AMPULA', 'J', false, true, 'antibioticos'),
  ('MERREM (MEROPENEM) 1g SOLUCION INYECTABLE FRASCO AMPULA', 'J', false, true, 'antibioticos'),
  ('MERMAVIE (MEROPENEM) 500mg SOLUCION INYECTABLE FRASCO AMPULA', 'J', false, true, 'antibioticos'),
  ('MERMAVIE (MEROPENEM) 1g SOLUCION INYECTABLE FRASCO AMPULA', 'J', false, true, 'antibioticos'),
  ('GI CEFALEXINA 500mg CAPSULAS CAJA C/20 (AMSA)', 'J', false, true, 'antibioticos'),
  ('FALOT (CEFALOTINA) 1g SOLUCION INYECTABLE FRASCO AMPULA', 'J', false, true, 'antibioticos'),
  ('SULOVAL (CEFEPIMA) 1g SOLUCION INYECTABLE AMPULA (KENNER)', 'J', false, true, 'antibioticos'),
  ('BIOMICS (CEFIXIMA) 400mg TAB CJA C/6 (SENOSIAN)', 'J', false, true, 'antibioticos'),
  ('BIOMICS (CEFIXIMA) 100mg/5ml SUSPENSION ORAL FCO C/50ml (ALTIA)', 'J', false, true, 'antibioticos'),
  ('GI CEFOTAXIMA 1gr SOLUCION INYECTABLE AMPULA (PHARMALIFE)', 'J', false, true, 'antibioticos'),
  ('GI CEFOTAXIMA 1gr SOL INY AMPULA (AMSA)', 'J', false, true, 'antibioticos'),
  ('GI CEFTAZIDIMA 1g SOLUCION INYECTABLE AMPULA (AMSA)', 'J', false, true, 'antibioticos'),
  ('ZAVICEFTA (CEFTAZIDIMA/AVIBACTAM) 2g/0.5g SOLUCION INYECTABLE FRASCO AMPULA', 'J', false, true, 'antibioticos'),
  ('ZERBAXA (CEFTOLOZANO/TAZOBACTAM) 1000mg/0.5mg SOLUCION INYECTABLE', 'J', false, true, 'antibioticos'),
  ('CEFTRIAXONA 1g SOLUCION INYECTABLE AMPULA (PISA)', 'J', false, true, 'antibioticos'),
  ('GI CEFUROXIMA 750mg/5ml SOLUCION INYECTABLE AMPULA (AMSA)', 'J', false, true, 'antibioticos'),
  ('CEFAGEN (CEFUROXIMA) 500mg TABLETAS C/10 (MAVER)', 'J', false, true, 'antibioticos'),
  ('ZEDESEN (CEFTIBUTENO) 400mg C/10 CAPSULAS (IPAL)', 'J', false, true, 'antibioticos'),
  ('FOSFOCIL (FOSFOMICINA) 500mg CAPSULAS CJA C/12 (CETUS)', 'J', false, true, 'antibioticos'),
  ('FOSFOCIL GU (FOSFOMICINA) 3g GRANULADO CJA C/1 SOBRE (ITRA)', 'J', false, true, 'antibioticos'),
  ('PREGNUS-UTI (FOSFOMICINA) 3g POLVO PARA SOLUCION ORAL', 'J', false, true, 'antibioticos'),
  ('FOSFOCIL INTRAVENOSO (FOSFOMICINA) 1g SOL INY AMPULA', 'J', false, true, 'antibioticos'),
  ('VANAURUS (VANCOMICINA) 500mg SOLUCION INYECTABLE AMPULA', 'J', false, true, 'antibioticos'),
  ('VANCOMICINA 500mg SOLUCION INYECTABLE FRASCO AMPULA (VITALIS)', 'J', false, true, 'antibioticos'),
  ('VARAMYN (VANCOMICINA) 500mg SOLUCION INYECTABLE AMPULA (KENER)', 'J', false, true, 'antibioticos'),
  ('GI CLINDAMICINA 300mg/2ml SOL INY AMP (NEOLPHARMA)', 'J', false, true, 'antibioticos'),
  ('GI CLINDAMICINA 600mg/4ml SOL INY AMP (AMSA)', 'J', false, true, 'antibioticos'),
  ('STENKIVAR (DAPTOMICINA) 500mg SOL INY FCO AMPULA (STENDHAL)', 'J', false, true, 'antibioticos'),
  ('GI MARZIVAG (AZITROMICINA) 500mg TABLETAS CJA C/3', 'J', false, true, 'antibioticos'),
  ('MACROZIT (AZITROMICINA) 500mg/5ml SOLUCION INYECTABLE AMPULA', 'J', false, true, 'antibioticos'),
  ('CHARYN (AZITROMICINA) 500mg TABLETAS CAJA CON 3', 'J', false, true, 'antibioticos'),
  ('KLARICID I.V. (CLARITROMICINA) 500mg SOLUCION INYECTABLE (ABBOTT)', 'J', false, true, 'antibioticos'),
  ('GI ERITROMICINA 500mg TABLETAS CJA C/20 (ALPHARMA)', 'J', false, true, 'antibioticos'),
  ('BIOFURIN (NITROFURANTOINA) 100mg CAPSULAS CJA C/40 (BIORESEARCH)', 'J', false, true, 'antibioticos'),
  ('FLAGYL (METRONIDAZOL) 500mg TAB CJA C/30 (SANFER)', 'J', false, true, 'antibioticos'),
  ('OTROZOL 500 (METRONIDAZOL) 500mg/100ml SOL INY FRASCO C/100ml', 'J', false, true, 'antibioticos'),
  ('LEZOPISA (LINEZOLID) 600mg SOLUCION INYECTABLE BOLSA CON 300ml', 'J', false, true, 'antibioticos'),
  ('ZYVOXAM (LINEZOLID) 2mg/ml SOLUCION INYECTABLE BOLSA CON 300ml', 'J', false, true, 'antibioticos'),
  ('YAPRINCA (LINEZOLID) 2mg/ml SOL INY BOLSA C/300ml', 'J', false, true, 'antibioticos'),
  ('GI LINEZOLID 600mg TABLETAS CAJA CON 10 TABLETAS (CAMBER)', 'J', false, true, 'antibioticos'),
  ('INVIONEZO (LINEZOLID) 2mg/ml SOL INY BOLSA C/300ml (FRESENIUS KABI)', 'J', false, true, 'antibioticos'),
  ('DAROGEN (COLISTIMETATO DE SODIO) 150mg SOL INY AMPULA (ARMADEXTRUM)', 'J', false, true, 'antibioticos'),
  ('CIPROBAC (CIPROFLOXACINO) 400mg SOLUCION INYECTABLE FRASCO', 'J', false, true, 'antibioticos'),
  ('SOPHIXIN DX OFTENO (DEXAMETASONA/CIPROFLOXACINO) 3mg/1mg/ml GOTAS OFTALMICAS FCO', 'J', false, true, 'antibioticos'),
  ('SOPHIXIN OFTENO (CIPROFLOXACINO) 3mg/mL GOTAS OFTALMICAS FRASCO C/5ml', 'J', false, true, 'antibioticos'),
  ('FLUONING (LEVOFLOXACINO) 500mg SOLUCION INYECTABLE FRASCO', 'J', false, true, 'antibioticos'),
  ('FLUONING (LEVOFLOXACINO) 750mg SOLUCION INYECTABLE FRASCO', 'J', false, true, 'antibioticos'),
  ('EVOCS III (LEVOFLOXACINO) 750mg SOLUCION INYECTABLE MINIBAG', 'J', false, true, 'antibioticos'),
  ('BREDELIN (LEVOFLOXACINO) 500mg TABLETAS CJA C/7', 'J', false, true, 'antibioticos'),
  ('GI LEVOFLOXACINO 750mg TABLETAS CJA C/7 (AMSA)', 'J', false, true, 'antibioticos'),
  ('GI LEVOFLOXACINO 500mg TABLETA CJA C/7 (AMSA)', 'J', false, true, 'antibioticos'),
  ('PIXIRIV (MOXIFLOXACINO) 400mg/250ml SOLUCION INYECTABLE FRASCO AMPULA', 'J', false, true, 'antibioticos'),
  ('RIFOCYNA (RIFAMICINA) 1g/100ml SOLUCION SPRAY FRASCO CON 20ml', 'J', false, true, 'antibioticos'),
  ('RIFADIN (RIFAMPICINA) 300mg CAPSULAS CAJA CON 16 CAPSULAS', 'J', false, true, 'antibioticos'),
  ('FLONORM (RIFAXIMINA) 200mg TABLETAS CJA C/28', 'J', false, true, 'antibioticos'),
  ('FLONORM (RIFAXIMINA) 550mg TABLETAS CJA C/14', 'J', false, true, 'antibioticos'),
  ('FLONORM (RIFAXIMINA) 400mg TABLETAS CJA C/14', 'J', false, true, 'antibioticos'),
  ('VIBRAMICINA (DOXICICLINA) 50mg CAP CJA C/28 (PFIZER)', 'J', false, true, 'antibioticos'),
  ('KENCICLEN (DOXICICLINA) 100mg CAP CJA C/10 (KENER)', 'J', false, true, 'antibioticos'),
  ('MINOCIN (MINOCICLINA) 100mg TABLETAS CAJA CON 12 TABLETAS', 'J', false, true, 'antibioticos'),
  ('GECIFHIL (TIGECICLINA) 50mg SOLUCION INYECTABLE FRASCO AMPULA', 'J', false, true, 'antibioticos'),
  ('TYGACIL (TIGECICLINA) 50mg SOL INY FCO AMPULA', 'J', false, true, 'antibioticos'),
  ('TETRA ATLANTIS (CLORHIDRATO DE TETRACICLINA) 250mg CJA C/16 CAPS', 'J', false, true, 'antibioticos'),
  ('AGUA DE IRRIGACION 500ml (TAPA AZUL) (PISA) (REF 4000255)', 'B', false, true, 'infusiones'),
  ('AGUA DE IRRIGACION 1000ml (PISA) (REF 4000258/4000253)', 'B', false, true, 'infusiones'),
  ('AGUA DE IRRIGACION 3000ml (PISA) (REF 4000261)', 'B', false, true, 'infusiones'),
  ('SOLUCION CS 0.9 % BAXTER 1000ml (BOLSA) INYECTABLE (BAXTER) (REFABB1324B)', 'B', false, true, 'infusiones'),
  ('SOLUCION CS 0.9% 250ml INYECTABLE (PISA) (REF4049546)', 'B', false, true, 'infusiones'),
  ('SOLUCION CS 0.9% 500ml INYECTABLE (PISA) (REF4000078)', 'B', false, true, 'infusiones'),
  ('SOLUCION CS 0.9% 1000ml INYECTABLE (PISA) (REF4000079)', 'B', false, true, 'infusiones'),
  ('SOLUCION CS 0.9% 50ml INYECTABLE (PISA ) (REF4000393)', 'B', false, true, 'infusiones'),
  ('SOLUCION CS 0.9% 100ml INYECTABLE (PISA) (REF4000394)', 'B', false, true, 'infusiones'),
  ('SOLUCION CS 0.9% 3000ml PARA IRRIGACION (PISA) (REF4006697)', 'B', false, true, 'infusiones'),
  ('SOLUCION DX-10 1000ml (GLUCOSA 10%) INYECTABLE (PISA) (REF4000107)', 'B', false, true, 'infusiones'),
  ('SOLUCION DX-10 500ml (GLUCOSA 10%) INYECTABLE (PISA) (REF4000108)', 'B', false, true, 'infusiones'),
  ('SOLUCION DX-5 250ml (GLUCOSA 5%) INYECTABLE (PISA) (REF4049551)', 'B', false, true, 'infusiones'),
  ('SOLUCION DX-5 500ml (GLUCOSA 5%) INYECTABLE (PISA) (REF4000103)', 'B', false, true, 'infusiones'),
  ('SOLUCION DX-5 1000ml (GLUCOSA 5%) INYECTABLE (PISA) (REF4000104)', 'B', false, true, 'infusiones'),
  ('SOLUCION DX-5 100ml (GLUCOSA 5%) INYECTABLE (PISA) (REF4000392)', 'B', false, true, 'infusiones'),
  ('SOLUCION DX-CS 500ml (SOLUCION MIXTA) (CLORURO DE SODIO 0.9%/GLUCOSA 5%) (PISA)', 'B', false, true, 'infusiones'),
  ('SOLUCION DX-CS 1000ml (SOLUCION MIXTA) (CLORURO DE SODIO 0.9%/GLUCOSA 5% (PISA)', 'B', false, true, 'infusiones'),
  ('SOLUCION DX-50 50ml (DEXTROCON) (GLUCOSA 50%) INYECTABLE (PISA) (REF4057049)', 'B', false, true, 'infusiones'),
  ('SOLUCION HARTMANN 250 ml INYECTABLE (PISA) (REF4000087)', 'B', false, true, 'infusiones'),
  ('SOLUCION HARTMANN 500 ml INYECTABLE (PISA) (REF4000088)', 'B', false, true, 'infusiones'),
  ('SOLUCION HARTMANN 1000 ml INYECTABLE (PISA) (REF4000089)', 'B', false, true, 'infusiones'),
  ('SOLUCION HARTMANN PI 500ml SOLUCION INYECTABLE FRASCO (4000072)', 'B', false, true, 'infusiones'),
  ('SOLUCION HARTMANN PI 1000ml INYECTABLE (PISA) (REF4000073)', 'B', false, true, 'infusiones'),
  ('VOLUVEN 500ml (HIDROXIETIL ALMIDON 6%) (FRESENIUS KABI)', 'B', false, true, 'infusiones'),
  ('SOLUCION OSMOROL 20 250ml (MANITOL) 20g/100ml (PISA) (REF4006463)', 'B', false, true, 'infusiones'),
  ('NULANZA (OLIGOMETALES ENDOVENOSOS) 10ml SOL INY FCO AMP (FRESENIUS)', 'B', false, true, 'infusiones'),
  ('SOLUCION NM-DX 5% 1000ml (SOLUCION NORMOSOL) (PISA) (REF4000098)', 'B', false, true, 'infusiones')
ON CONFLICT (nombre) DO UPDATE SET
  categoria = EXCLUDED.categoria,
  activo    = true;

-- Verificación: cuántos por categoría
SELECT categoria, count(*) FROM public.pharmacy_med_catalog
WHERE categoria IS NOT NULL GROUP BY categoria ORDER BY categoria;
