-- ══════════════════════════════════════════════════════════════════
-- RIESGOS REALES — Hospital Santa Margarita
-- Fuente: Matriz de Riesgos por Proceso (PDF, 46 pp.)
-- Ejecutar en: Supabase → SQL Editor
--
-- Este script:
--   1. ACTUALIZA los 6 procesos existentes con riesgos reales del PDF
--   2. INSERTA 7 procesos nuevos identificados en el PDF
--   3. NO elimina ningún dato previo
-- ══════════════════════════════════════════════════════════════════

-- ─── HELPER: actualizar riesgos de un proceso por nombre ──────────
-- (usamos UPDATE … WHERE name = '...' para cada proceso existente)

-- ══════════════════════════════════════════════════════════════════
-- SECCIÓN 1: ACTUALIZAR PROCESOS EXISTENTES
-- ══════════════════════════════════════════════════════════════════

-- ── 1a. Quirófano y Anestesiología (PR-QX + PR-CEYE) ─────────────
UPDATE risk_processes SET
  process_owner = 'Jefe de Quirófano / Jefatura de Enfermería',
  description   = 'Realización de procedimientos quirúrgicos, manejo anestésico y gestión de central de equipos y esterilización (CEYE).',
  risks = '[
    {"id":"qx-01","type":"riesgo","description":"Mala ejecución de la técnica anestésica (ASC 3.2)","cause":"Error en la técnica por parte del anestesiólogo o condiciones del paciente","effect":"Complicaciones graves, riesgo de muerte del paciente","probability":2,"impact":5,"action_plan":"Cumplir con la Normativa. Realizar valoración preanestésica completa antes de cada procedimiento.","responsible":"Médico Anestesiólogo","due_date":"2025-12-31","status":"en_control"},
    {"id":"qx-02","type":"riesgo","description":"Estado general del paciente con complicaciones no previstas en cirugía","cause":"Valoración preanestésica insuficiente o incompleta","effect":"Complicaciones intraoperatorias, prolongación del procedimiento, riesgo de muerte","probability":3,"impact":4,"action_plan":"Realizar valoración preanestésica completa. Cumplir con la Normativa vigente.","responsible":"Médico Anestesiólogo","due_date":"2025-12-31","status":"en_control"},
    {"id":"qx-03","type":"riesgo","description":"Uso de ropa quirúrgica sucia en área de quirófano","cause":"Error en el flujo de transfer, mal etiquetado de bultos","effect":"Contaminación cruzada, infección del sitio quirúrgico","probability":1,"impact":5,"action_plan":"Estandarización del etiquetado de bultos para identificar los sucios de los limpios. Revisión del registro del operador de GPH.","responsible":"Jefe de Quirófano","due_date":"2025-11-30","status":"en_control"},
    {"id":"qx-04","type":"riesgo","description":"Lesión del operativo al juntar instrumental corto-punzante con el bulto","cause":"Manejo inadecuado y desecho sin precaución del material corto-punzante","effect":"Accidente laboral, exposición a riesgo biológico","probability":3,"impact":3,"action_plan":"Manejo, utilización y desecho del material corto-punzante con extremado cuidado. Capacitación al personal.","responsible":"Jefe de Quirófano","due_date":"2025-11-30","status":"en_control"},
    {"id":"qx-05","type":"riesgo","description":"Contaminación de área blanca por no reemplazar accesorios dañados (CEYE)","cause":"Falta de supervisión del estado de los accesorios de ingreso a quirófano","effect":"Contaminación del área estéril, riesgo de IAAS","probability":2,"impact":3,"action_plan":"Supervisar el cambio de accesorios por daño o contaminación.","responsible":"Jefe de Quirófano","due_date":"2025-12-31","status":"en_control"},
    {"id":"qx-06","type":"riesgo","description":"Infecciones cruzadas por no cambiar uniforme quirúrgico contaminado (CEYE)","cause":"Incumplimiento del protocolo de cambio de uniforme tras cirugía contaminada","effect":"Contaminación del área quirúrgica, riesgo de IAAS","probability":2,"impact":4,"action_plan":"Capacitar sobre la correcta manera de portar uniforme quirúrgico. Supervisión del cumplimiento.","responsible":"Jefe de Quirófano","due_date":"2025-11-30","status":"en_control"},
    {"id":"qx-07","type":"riesgo","description":"Lavado inadecuado del instrumental quirúrgico (CEYE)","cause":"Omisión de actividades durante el lavado, técnica incorrecta","effect":"Esterilización deficiente, riesgo de infección del sitio quirúrgico","probability":2,"impact":4,"action_plan":"Reforzar el proceso correcto para lavado de material. Poner especial cuidado al sumergir, sacar, tallar y secar instrumental afilado.","responsible":"Jefe de CEYE","due_date":"2025-11-30","status":"en_control"},
    {"id":"qx-08","type":"riesgo","description":"Omisión o manejo inadecuado del proceso de esterilización (CEYE)","cause":"Incumplimiento de la bitácora de mantenimiento de autoclaves","effect":"Material no estéril utilizado en procedimientos, infección grave del paciente","probability":2,"impact":4,"action_plan":"Cumplir con la bitácora de mantenimiento de las autoclaves. No exceder la capacidad de la autoclave. Respetar los tiempos de esterilización.","responsible":"Jefe de CEYE","due_date":"2025-11-30","status":"en_control"},
    {"id":"qx-09","type":"riesgo","description":"Salida de bultos mojados por no respetar tiempos de esterilización o capacidad de la autoclave","cause":"Sobrecarga de la autoclave o tiempos insuficientes de secado","effect":"Material considerado contaminado, retraso en cirugías, riesgo de infección","probability":2,"impact":4,"action_plan":"No exceder la capacidad de la autoclave. Respetar los tiempos de esterilización y secado.","responsible":"Jefe de CEYE","due_date":"2025-11-30","status":"en_control"}
  ]',
  updated_at = now()
WHERE name = 'Quirófano y Anestesiología';

-- ── 1b. Imagenología y Diagnóstico (PR-RX) ───────────────────────
UPDATE risk_processes SET
  process_owner = 'Jefe de Imagenología / Radiología',
  description   = 'Estudios de diagnóstico por imagen: estudios contrastados, radiografías simples (hospitalización y externos) con y sin condición COVID.',
  risks = '[
    {"id":"rx-01","type":"riesgo","description":"Registro erróneo del paciente (nombre, edad, estudio solicitado) al inicio del proceso","cause":"Falta de verificación de datos antes de finalizar el registro en el sistema","effect":"Estudio realizado a paciente equivocado, error diagnóstico, responsabilidad médico-legal","probability":3,"impact":3,"action_plan":"Corroborar los datos del paciente antes de finalizar el registro en el sistema. Doble verificación en recepción.","responsible":"Jefe de Imagenología","due_date":"2025-11-30","status":"en_control"},
    {"id":"rx-02","type":"riesgo","description":"Errores técnicos en la realización del estudio (radiología o contrastados)","cause":"Falta de verificación del registro correcto antes de iniciar el estudio","effect":"Estudio no útil diagnósticamente, necesidad de repetir con exposición adicional al paciente","probability":2,"impact":3,"action_plan":"Corroborar con el paciente el registro correcto de los datos antes de finalizar el registro en el equipo de rayos X.","responsible":"Jefe de Imagenología","due_date":"2025-11-30","status":"en_control"},
    {"id":"rx-03","type":"riesgo","description":"Entrega errónea de estudios al paciente incorrecto","cause":"Falta de verificación de datos antes de entregar el estudio en CD","effect":"Entrega de resultados a paciente equivocado, confidencialidad comprometida, error diagnóstico","probability":2,"impact":4,"action_plan":"Verificar datos del paciente antes de entregar el estudio en CD. Confirmar la lectura y firma del consentimiento informado.","responsible":"Jefe de Imagenología","due_date":"2025-11-30","status":"en_control"},
    {"id":"rx-04","type":"riesgo","description":"Efectos secundarios al medio de contraste empleado en el estudio","cause":"Reacción alérgica o adversa al medio de contraste intravenoso","effect":"Reacción anafiláctica, daño renal, evento adverso grave","probability":2,"impact":5,"action_plan":"Confirmar la lectura y firma del consentimiento informado por parte del paciente o familiar. Tener protocolo de manejo de reacciones al contraste disponible.","responsible":"Médico Radiólogo","due_date":"2025-11-30","status":"en_control"},
    {"id":"rx-05","type":"riesgo","description":"Error en el registro de correo electrónico o número de celular para envío de estudios","cause":"Datos de contacto incorrectos o incompletos al momento del registro","effect":"El paciente no recibe sus resultados, retraso diagnóstico","probability":2,"impact":2,"action_plan":"Corroborar el correo electrónico y/o número de celular antes de despedir al paciente.","responsible":"Jefe de Imagenología","due_date":"2025-12-31","status":"en_control"},
    {"id":"rx-06","type":"riesgo","description":"Cobro erróneo de los estudios contrastados solicitados (urgencias)","cause":"Falta de verificación de los estudios facturados vs los realizados","effect":"Pérdida de ingresos, inconformidad del paciente, problemas de facturación","probability":3,"impact":2,"action_plan":"Confirmar con el paciente la correcta identificación antes de realizar el estudio. Revisión de cobros generados vs estudios realizados.","responsible":"Jefe de Imagenología","due_date":"2025-12-31","status":"identificado"}
  ]',
  updated_at = now()
WHERE name = 'Imagenología y Diagnóstico';

-- ── 1c. Farmacia y Suministro de Medicamentos (PR-FH) ─────────────
UPDATE risk_processes SET
  process_owner = 'Jefe de Farmacia Hospitalaria',
  description   = 'Conciliación de medicamentos, dispensación, prescripción segura, uso seguro de medicamentos multidosis, identificación de cuasifallas y monitorización de medicamentos en cuadro básico.',
  risks = '[
    {"id":"fh-01","type":"riesgo","description":"Recabar información incompleta o incorrecta de los medicamentos que toma el paciente en casa (PR-FH-01)","cause":"Habilidades de comunicación insuficientes del farmacéutico, datos incompletos en el expediente","effect":"Conciliación incorrecta, duplicidad o interacciones medicamentosas no detectadas","probability":3,"impact":3,"action_plan":"Desarrollar y perfeccionar las habilidades de comunicación de los farmacéuticos. Contar con la plantilla completa y capacitada.","responsible":"Jefe de Farmacia","due_date":"2025-11-30","status":"en_control"},
    {"id":"fh-02","type":"riesgo","description":"Conciliación de medicamentos al ingreso realizada pasadas las 4 horas (PR-FH-01)","cause":"Carga de trabajo excesiva, priorización incorrecta de actividades","effect":"Decisiones clínicas sin información completa de medicación domiciliaria","probability":2,"impact":3,"action_plan":"Contar con la plantilla de farmacéuticos completa y capacitada para realizar la conciliación de la medicación en tiempo.","responsible":"Jefe de Farmacia","due_date":"2025-11-30","status":"en_control"},
    {"id":"fh-03","type":"riesgo","description":"Errores de medicación derivados de malas prácticas en la prescripción (PR-FH-03)","cause":"Prescripción incompleta, ilegible o con abreviaturas peligrosas","effect":"Evento adverso medicamentoso, daño al paciente","probability":3,"impact":4,"action_plan":"Revisión, evaluación, detección y comunicación oportuna y efectiva al Médico Tratante de errores potenciales en la prescripción.","responsible":"Jefe de Farmacia","due_date":"2025-11-15","status":"en_control"},
    {"id":"fh-04","type":"riesgo","description":"Errores de medicación derivados de malas prácticas en la transcripción de indicaciones médicas (PR-FH-04)","cause":"Transcripción incorrecta de indicaciones, letra ilegible, indicación incompleta","effect":"Administración de medicamento erróneo o dosis incorrecta","probability":3,"impact":4,"action_plan":"Revisión, evaluación, detección y comunicación oportuna y efectiva al Médico de Guardia de errores potenciales en la transcripción. Aclarar oportunamente cualquier duda, error y/o indicación incompleta.","responsible":"Jefe de Farmacia","due_date":"2025-11-15","status":"en_control"},
    {"id":"fh-05","type":"riesgo","description":"Riesgo a la salud del paciente derivado de un PRM o RNM no atendido (PR-FH-05)","cause":"Falta de identificación oportuna de problemas relacionados con medicamentos","effect":"Daño al paciente, evento adverso grave","probability":2,"impact":5,"action_plan":"Personal farmacéutico capacitado con competencias para identificar PRM y RNM. Intervención farmacéutica adecuada y asertiva.","responsible":"Jefe de Farmacia","due_date":"2025-11-30","status":"en_control"},
    {"id":"fh-06","type":"riesgo","description":"Contaminación microbiológica de medicamentos multidosis por compartirlos entre pacientes o usar agujas no estériles (PR-FH-06)","cause":"Incumplimiento del protocolo de uso de medicamentos multidosis","effect":"Infección al paciente asociada a la atención sanitaria","probability":2,"impact":4,"action_plan":"Manipular correctamente los medicamentos multidosis. Realizar los Correctos de Enfermería y cumplir con la Meta Internacional de Seguridad del Paciente 6 (MISP.6).","responsible":"Jefe de Farmacia","due_date":"2025-11-30","status":"en_control"},
    {"id":"fh-07","type":"riesgo","description":"Cultura organizacional punitiva que no favorece la comunicación de cuasifallas y errores de medicación (PR-FH-08)","cause":"Miedo a consecuencias disciplinarias, falta de cultura de seguridad","effect":"Errores no notificados, pérdida de oportunidad de aprendizaje y mejora","probability":3,"impact":3,"action_plan":"Analizar el error sin considerar a quien intervino, para identificar cómo y por qué se ha producido. Mejorar la cultura organizacional para incrementar la notificación.","responsible":"Director General","due_date":"2026-01-31","status":"identificado"},
    {"id":"fh-08","type":"riesgo","description":"Inefectividad o inseguridad del medicamento recién agregado al cuadro básico (PR-FH-09)","cause":"Vigilancia insuficiente de la respuesta del paciente a medicamentos nuevos","effect":"Daño al paciente, necesidad de retiro urgente del medicamento del cuadro básico","probability":2,"impact":4,"action_plan":"Contar con profesionales de la salud formados para detectar si el medicamento está consiguiendo el objetivo terapéutico. Análisis de errores y establecimiento de estrategias para disminuirlos.","responsible":"Jefe de Farmacia","due_date":"2025-12-31","status":"identificado"},
    {"id":"fh-09","type":"riesgo","description":"Duplicidad en la administración de medicamento del paciente (PR-FH-02)","cause":"Falta de conciliación al ingreso y cambios de médico tratante","effect":"Sobredosis, intoxicación, riesgo para la salud del paciente","probability":2,"impact":4,"action_plan":"Realizar de manera oportuna y efectiva la conciliación de la medicación al ingreso.","responsible":"Jefe de Farmacia","due_date":"2025-11-30","status":"en_control"}
  ]',
  updated_at = now()
WHERE name = 'Farmacia y Suministro de Medicamentos';

-- ── 1d. Limpieza y Gestión Ambiental (PR-IN + PR-SG) ─────────────
UPDATE risk_processes SET
  process_owner = 'Jefe de Servicios Generales / Intendencia',
  description   = 'Aseo tipo cultivo, aseo exhaustivo supervisado y nebulizado, limpieza y desinfección de quirófano, manejo de RPBI, productos químicos, recolección de residuos peligrosos y fumigación.',
  risks = '[
    {"id":"in-01","type":"riesgo","description":"Salas quirúrgicas en condiciones antihigiénicas por limpieza y desinfección insuficiente (PR-IN-03)","cause":"Personal sin capacitación en técnicas de limpieza de áreas críticas","effect":"Riesgo de infecciones hospitalarias, contaminación del área quirúrgica","probability":2,"impact":4,"action_plan":"Capacitación al personal sobre las técnicas de limpieza en las distintas áreas. Supervisión continua con listas de verificación.","responsible":"Jefe de Intendencia","due_date":"2025-11-30","status":"en_control"},
    {"id":"in-02","type":"riesgo","description":"Riesgos a la salud del personal por exposición a agentes biológicos en área de quirófano (PR-IN-03)","cause":"Manejo inadecuado de materiales biológicos, falta de EPP","effect":"Accidente laboral, contagio de enfermedades infecciosas","probability":3,"impact":4,"action_plan":"Uso de equipo de protección personal. Capacitación en manejo adecuado de RPBI.","responsible":"Jefe de Intendencia","due_date":"2025-11-30","status":"en_control"},
    {"id":"in-03","type":"riesgo","description":"Clasificación y separación errónea de Residuos Peligrosos Biológico-Infecciosos (RPBI) (PR-SG-07)","cause":"Personal no capacitado en identificación y separación de RPBI","effect":"Sanciones administrativas, contaminación cruzada, riesgo biológico","probability":3,"impact":4,"action_plan":"Capacitación para la identificación, separación y envasado de RPBI. Supervisión de contenedores de RPBI en cada área.","responsible":"Jefe de Servicios Generales","due_date":"2025-11-30","status":"en_control"},
    {"id":"in-04","type":"riesgo","description":"Contaminación y daño a la salud por manipulación inadecuada de RPBI (PR-SG-07)","cause":"Manejo incorrecto de residuos biológico-infecciosos, falta de EPP adecuado","effect":"Riesgo biológico para personal y pacientes, sanciones COFEPRIS/SEMARNAT","probability":3,"impact":4,"action_plan":"Capacitar al personal para el manejo adecuado de RPBI y el uso correcto del equipo de protección personal.","responsible":"Jefe de Servicios Generales","due_date":"2025-11-30","status":"en_control"},
    {"id":"in-05","type":"riesgo","description":"Accidentes de trabajo por mal manejo y almacenamiento de productos químicos (PR-SG-06)","cause":"Falta de capacitación en manejo de químicos, ausencia de hojas de datos de seguridad","effect":"Intoxicación, irritación cutánea, riesgo ambiental","probability":3,"impact":4,"action_plan":"Capacitar al personal para el manejo adecuado de productos químicos. Existencia de las hojas de datos de seguridad de cada sustancia en cada área.","responsible":"Jefe de Servicios Generales","due_date":"2025-11-30","status":"en_control"},
    {"id":"in-06","type":"riesgo","description":"Contaminación por agentes patógenos en el agua por niveles de cloro inadecuados (PR-SG-08/21)","cause":"Falta de monitoreo frecuente de niveles de cloro residual","effect":"Riesgo de enfermedades transmitidas por el agua, sanciones sanitarias","probability":2,"impact":4,"action_plan":"Monitoreo frecuente de los niveles de cloro residual en el agua. Medidas correctivas y control constante hasta tener los parámetros óptimos. Documentación de bitácoras mensuales.","responsible":"Jefe de Servicios Generales","due_date":"2025-11-30","status":"en_control"},
    {"id":"in-07","type":"riesgo","description":"Mal manejo de traslado y almacenamiento de residuos peligrosos (PR-SG-14)","cause":"Personal no capacitado, incumplimiento de procedimientos de traslado","effect":"Sanciones de autoridades competentes, riesgo ambiental y de salud","probability":3,"impact":4,"action_plan":"Capacitar al personal para el manejo adecuado de residuos peligrosos y uso del equipo de protección. Control administrativo en base a bitácoras.","responsible":"Jefe de Servicios Generales","due_date":"2025-11-30","status":"en_control"},
    {"id":"in-08","type":"riesgo","description":"Generación de plagas por fauna nociva en áreas del hospital (PR-SG-20)","cause":"Control de fumigación insuficiente o irregular","effect":"Riesgo de contaminación, sanciones sanitarias, daño a la imagen institucional","probability":2,"impact":3,"action_plan":"Control de fumigación mensual y atención a las incidencias en su momento. Tomar medidas preventivas para la fumigación del área con el equipo adecuado.","responsible":"Jefe de Servicios Generales","due_date":"2025-12-31","status":"en_control"}
  ]',
  updated_at = now()
WHERE name = 'Limpieza y Gestión Ambiental';

-- ── 1e. Mantenimiento de Infraestructura y Equipos (PR-SG) ────────
UPDATE risk_processes SET
  process_owner = 'Jefe de Mantenimiento / Servicios Generales',
  description   = 'Mantenimiento correctivo y preventivo de equipos e infraestructura, mantenimiento preventivo externo, supervisión en construcción y remodelación, monitoreo de servicios básicos y gestión de la planta de energía eléctrica.',
  risks = '[
    {"id":"sg-01","type":"riesgo","description":"Accidentes de trabajo durante mantenimiento correctivo de equipos o infraestructura (PR-SG-04)","cause":"Falta de uso de equipo de protección personal adecuado a la actividad","effect":"Lesiones al personal, ausentismo, responsabilidad legal","probability":3,"impact":4,"action_plan":"Usar el equipo de protección personal correspondiente a la actividad que se ejecutará. Capacitación en seguridad laboral.","responsible":"Jefe de Mantenimiento","due_date":"2025-11-30","status":"en_control"},
    {"id":"sg-02","type":"riesgo","description":"Deterioro de equipos o áreas requiriendo mantenimiento correctivo con presupuesto alto (PR-SG-05)","cause":"Falta de programa de mantenimiento preventivo o incumplimiento del mismo","effect":"Costos elevados de reparación, interrupción de servicios","probability":3,"impact":3,"action_plan":"Supervisión del correcto mantenimiento preventivo a equipos y áreas. Programa anual de mantenimiento preventivo.","responsible":"Jefe de Mantenimiento","due_date":"2025-12-31","status":"en_control"},
    {"id":"sg-03","type":"riesgo","description":"Riesgos eléctricos durante mantenimiento: shock eléctrico, quemaduras (PR-SG-09)","cause":"Falta de uso de equipo de protección personal eléctrico","effect":"Accidente laboral grave, quemaduras, electrocución","probability":2,"impact":4,"action_plan":"Uso de equipo de protección personal: guantes y calzado de seguridad. Capacitación en precauciones y técnicas de trabajo eléctrico.","responsible":"Jefe de Mantenimiento","due_date":"2025-11-30","status":"en_control"},
    {"id":"sg-04","type":"riesgo","description":"No activarse algún detector de humo en caso de incidencia (PR-SG-10)","cause":"Falta de revisión mensual de detectores de humo","effect":"Multas por omisión de revisión, riesgo de no detectar incendios oportunamente","probability":2,"impact":4,"action_plan":"Revisión mensual de cada detector de humo. Llevar y resguardar el registro de las bitácoras de revisión.","responsible":"Jefe de Mantenimiento","due_date":"2025-11-15","status":"en_control"},
    {"id":"sg-05","type":"riesgo","description":"Desabasto de gases medicinales (oxígeno, nitrógeno) en el hospital (PR-SG-11)","cause":"Falta de monitoreo diario del stock de gas medicinal","effect":"Interrupción de atención a pacientes críticos, riesgo de muerte","probability":2,"impact":5,"action_plan":"Conteo diario del stock de gas medicinal. Coordinación oportuna con el proveedor para resurtido.","responsible":"Jefe de Mantenimiento","due_date":"2025-11-15","status":"en_control"},
    {"id":"sg-06","type":"riesgo","description":"Desabasto de agua en el hospital (PR-SG-11)","cause":"Falta de control diario de niveles de agua en cisternas","effect":"Interrupción de servicios clínicos y sanitarios, riesgo de IAAS","probability":3,"impact":4,"action_plan":"Control diario de niveles de agua en cisternas. Monitoreo rutinario del consumo diario de agua.","responsible":"Jefe de Mantenimiento","due_date":"2025-11-30","status":"en_control"},
    {"id":"sg-07","type":"riesgo","description":"Falla en la planta de energía eléctrica del hospital (PR-SG-22)","cause":"Falta de mantenimiento preventivo anual o monitoreo diario de la planta","effect":"Interrupción de quirófano, UCI y laboratorio — riesgo de muerte de pacientes","probability":2,"impact":5,"action_plan":"Ejecución de mantenimiento preventivo anual y monitoreo diario de las condiciones de la planta de energía eléctrica.","responsible":"Jefe de Mantenimiento","due_date":"2025-11-15","status":"en_control"},
    {"id":"sg-08","type":"riesgo","description":"No cumplir con la normativa de las autoridades competentes en construcción y remodelación (PR-SG-16)","cause":"Contratación de empresa sin las certificaciones requeridas","effect":"Sanciones de autoridades, suspensión de obra, multas","probability":2,"impact":4,"action_plan":"Certificados de capacitación presentados por la empresa seleccionada. Exámenes toxicológicos presentados por la empresa contratada.","responsible":"Jefe de Mantenimiento","due_date":"2025-12-31","status":"identificado"},
    {"id":"sg-09","type":"riesgo","description":"Contratar prestadores de servicios de baja calidad o con desempeño no confiable (PR-SG-24)","cause":"Falta de proceso de evaluación de prestadores de servicio","effect":"Servicios deficientes, riesgo de daños a equipos o instalaciones","probability":2,"impact":4,"action_plan":"Considerar prestadores de servicios con referencias, renombrados y buen historial. Realizar un análisis de criterios en la evaluación.","responsible":"Administración","due_date":"2025-12-31","status":"identificado"}
  ]',
  updated_at = now()
WHERE name = 'Mantenimiento de Infraestructura y Equipos';

-- ── 1f. Recursos Humanos y Capacitación (PR-CH) ───────────────────
UPDATE risk_processes SET
  process_owner = 'Jefatura de Capital Humano',
  description   = 'Reclutamiento, selección y contratación de personal (S.Q.E.6), inducción, capacitación y desarrollo del capital humano del hospital.',
  risks = '[
    {"id":"ch-01","type":"riesgo","description":"Tomar la entrevista como único filtro para la contratación de personal (PR-CH-01)","cause":"Proceso de selección simplificado sin evaluaciones complementarias","effect":"Contratación de personal no competente, riesgos en la calidad de atención y seguridad del paciente","probability":3,"impact":4,"action_plan":"Se emplea herramienta de evaluación de conocimientos, psicométrica y prácticos como filtros adicionales a la entrevista.","responsible":"Jefatura Capital Humano","due_date":"2025-12-31","status":"en_control"},
    {"id":"ch-02","type":"riesgo","description":"Contratar candidato con documentación apócrifa (cédula, título, certificados) (PR-CH-01)","cause":"Verificación insuficiente de la autenticidad de documentos habilitantes","effect":"Personal sin habilitación legal ejerciendo, responsabilidad institucional, sanciones","probability":2,"impact":4,"action_plan":"Validación de documentación por medio de medios electrónicos (RENIECYT, SSP, SEP). Verificación de cédulas profesionales en RENAP.","responsible":"Jefatura Capital Humano","due_date":"2025-12-31","status":"en_control"},
    {"id":"ch-03","type":"riesgo","description":"Candidato que proporciona información falsa sobre anteriores empleos (PR-CH-01)","cause":"Falta de verificación de referencias laborales directamente con empleadores anteriores","effect":"Contratación de personal con antecedentes negativos o incompetente","probability":2,"impact":4,"action_plan":"Solicitar referencia en sus anteriores trabajos, teniendo contacto directamente con la empresa anterior.","responsible":"Jefatura Capital Humano","due_date":"2025-12-31","status":"en_control"},
    {"id":"ch-04","type":"riesgo","description":"Alta rotación de personal clave en áreas críticas","cause":"Condiciones laborales o salariales no competitivas con el mercado","effect":"Pérdida de conocimiento, impacto en calidad de atención, costos de reclutamiento elevados","probability":3,"impact":4,"action_plan":"Encuesta de clima laboral anual. Plan de retención para personal clave. Análisis de salarios vs mercado.","responsible":"Jefatura Capital Humano","due_date":"2026-01-31","status":"identificado"},
    {"id":"ch-05","type":"oportunidad","description":"Programa de desarrollo de competencias alineado al SGC para cerrar brechas de capacitación","cause":"Identificación de necesidades de capacitación a través del SGC","effect":"Personal más competente, menor incidencia de no conformidades por factor humano","probability":4,"impact":4,"action_plan":"Plan anual de capacitación basado en análisis de brechas. Incluir ISO 9001, seguridad del paciente y habilidades técnicas.","responsible":"Jefatura Capital Humano","due_date":"2026-01-31","status":"identificado"}
  ]',
  updated_at = now()
WHERE name = 'Recursos Humanos y Capacitación';


-- ══════════════════════════════════════════════════════════════════
-- SECCIÓN 2: INSERTAR PROCESOS NUEVOS DEL PDF
-- ══════════════════════════════════════════════════════════════════

INSERT INTO risk_processes (name, process_type, process_owner, description, sort_order, risks) VALUES

-- ── 2a. Prevención y Control de Infecciones (UVEH) ───────────────
('Prevención y Control de Infecciones (UVEH)', 'misional',
 'Responsable de Epidemiología / Comité de Infecciones',
 'Vigilancia epidemiológica hospitalaria, control de IAAS, aislamiento de pacientes infecciosos e inmunodeprimidos, medidas de precaución estándar, manejo de RPBI clínico, manejo adecuado de alimentos, construcciones y medicación (PCI).',
 16,
'[
  {"id":"uv-01","type":"riesgo","description":"No realizar seguimiento a la realización del proceso de lavado de manos (PR-UV-08)","cause":"Falta de fechas específicas de capacitación y evaluación del proceso de lavado de manos","effect":"Incumplimiento de la higiene de manos OMS, incremento del riesgo de IAAS","probability":3,"impact":3,"action_plan":"Programar fechas específicas de capacitación y de evaluación de seguimiento del proceso de lavado de manos.","responsible":"Responsable UVEH","due_date":"2025-11-30","status":"en_control"},
  {"id":"uv-02","type":"riesgo","description":"Accidentes laborales por riesgos biológicos (punzocortante) — falta de protocolo de seguimiento (PR-UV-09)","cause":"No conocer el protocolo de seguimiento en caso de accidente laboral por punzocortante / no notificar en tiempo y forma","effect":"Manejo inapropiado del accidente, riesgo de transmisión de enfermedades infecciosas al trabajador","probability":2,"impact":4,"action_plan":"Explicar claramente el proceso a los colaboradores para brindar la atención oportuna.","responsible":"Responsable UVEH","due_date":"2025-11-30","status":"en_control"},
  {"id":"uv-03","type":"riesgo","description":"No apego por parte de los colaboradores a las indicaciones del comité ante alerta epidemiológica (PR-UV-10)","cause":"Desconocimiento de nuevos procesos, incumplimiento de indicaciones del comité","effect":"Propagación de brotes epidémicos, incumplimiento normativo","probability":3,"impact":4,"action_plan":"Estricto apoyo de cada departamento para el cumplimiento de objetivos del comité. Constante capacitación sobre nuevos procesos.","responsible":"Responsable UVEH","due_date":"2025-11-30","status":"en_control"},
  {"id":"uv-04","type":"riesgo","description":"Personal clínico no respeta las medidas de aislamiento para pacientes infecciosos (PR-UV-11)","cause":"Incumplimiento de medidas establecidas, falta de insumos adecuados para el aislamiento","effect":"Transmisión de enfermedades infecciosas a otros pacientes y al personal","probability":3,"impact":4,"action_plan":"Capacitación continua sobre la importancia de las medidas precautorias. Garantizar abastecimiento constante de insumos.","responsible":"Responsable UVEH","due_date":"2025-11-30","status":"en_control"},
  {"id":"uv-05","type":"riesgo","description":"Personal no respeta las precauciones estándar para pacientes inmunodeprimidos (PR-UV-12)","cause":"Incumplimiento de lo establecido en el documento, falta de insumos para el aislamiento","effect":"Infecciones en pacientes inmunodeprimidos, complicaciones graves","probability":3,"impact":4,"action_plan":"Capacitación continua sobre la importancia de las precauciones estándar. Garantizar abastecimiento constante de insumos.","responsible":"Responsable UVEH","due_date":"2025-11-30","status":"en_control"},
  {"id":"uv-06","type":"riesgo","description":"Incidencia recurrente de IAAS y riesgos laborales por falta de insumos de protección (PCI.3)","cause":"Falta de identificación oportuna de IAAS, insumos insuficientes para protección de colaboradores","effect":"Deterioro de la salud de pacientes y personal, mayor estancia hospitalaria, costos elevados","probability":3,"impact":4,"action_plan":"Identificación oportuna de IAAS para aplicar medidas preventivas. Monitoreo frecuente de los insumos necesarios para la atención sanitaria.","responsible":"Responsable UVEH","due_date":"2025-11-30","status":"en_control"},
  {"id":"uv-07","type":"riesgo","description":"Aumento de IAAS e identificación tardía / sanciones COPRISIAL por incumplimiento compromisos CODECIN (PCI.4)","cause":"Capacitación continua insuficiente, adiestramiento deficiente en epidemiología, incumplimiento de compromisos","effect":"Daño a pacientes, sanciones administrativas de COPRISIAL/CODECIN","probability":3,"impact":5,"action_plan":"Capacitación continua al personal clínico sobre acciones de prevención y control de infecciones. Adiestramiento del personal de epidemiología. Compromiso de jefes de departamento en implementación de acciones preventivas.","responsible":"Responsable UVEH","due_date":"2025-11-15","status":"en_control"},
  {"id":"uv-08","type":"riesgo","description":"Brote de infecciones por incumplimiento del protocolo de medidas de precaución estándar (PCI.5 / PR-UV-15)","cause":"Resistencia del personal al uso adecuado de EPP, falta de insumos y equipo de protección","effect":"Brote de enfermedades infectocontagiosas, riesgo de inmunodefresión","probability":2,"impact":5,"action_plan":"Supervisión constante de los procesos en pacientes con enfermedades infectocontagiosas. Capacitación continua del personal clínico. Inventario constante por parte de Farmacia para garantizar disponibilidad de insumos.","responsible":"Responsable UVEH","due_date":"2025-11-15","status":"en_control"},
  {"id":"uv-09","type":"riesgo","description":"Riesgo de infecciones en pacientes por construcciones, remodelaciones y obras (PCI.11 / PR-UV-18)","cause":"Exposición a polvo y humedad por obras, incumplimiento de normativas de STyPS, SEMARNAT, Bomberos, COPRISIAL","effect":"Infecciones respiratorias en pacientes y personal, sanciones por múltiples dependencias","probability":3,"impact":4,"action_plan":"Realización de análisis de riesgo antes del inicio de cualquier construcción o remodelación. Supervisión continua sobre la correcta aplicación de los procesos internos.","responsible":"Responsable UVEH","due_date":"2025-12-31","status":"identificado"},
  {"id":"uv-10","type":"riesgo","description":"Brotes de enfermedad respiratoria en pacientes y colaboradores por incumplimiento de protocolo (PR-UV-23)","cause":"Renuencia de médicos y familiares a aceptar el protocolo, no respeto del aislamiento de vía aérea","effect":"Brotes de enfermedad respiratoria, impacto en la capacidad operativa del hospital","probability":2,"impact":5,"action_plan":"Respaldo de dirección médica y dirección general para que se cumpla lo establecido. Supervisión del protocolo de aislamiento establecido.","responsible":"Responsable UVEH","due_date":"2025-11-30","status":"en_control"},
  {"id":"uv-11","type":"riesgo","description":"Infecciones en pacientes y colaboradores por mal ejecución de procesos en hemodiálisis (PCI.14 / PR-UV-22)","cause":"Falta de conocimientos en el manejo de pacientes de hemodiálisis, mala calidad del agua","effect":"Intoxicaciones, infecciones graves, riesgo de muerte en pacientes de hemodiálisis","probability":2,"impact":5,"action_plan":"Capacitación obligatoria de 3 semanas a cargo de la jefatura de enseñanza de enfermería. Supervisión continua de los niveles de cloración del agua y corrección en caso de desviaciones.","responsible":"Jefatura de Enfermería","due_date":"2025-11-30","status":"en_control"}
]'),

-- ── 2b. Nutrición y Dietética ─────────────────────────────────────
('Nutrición y Dietética', 'apoyo',
 'Jefe de Nutrición y Dietética',
 'Requisición de alimentos, identificación de errores de indicación médica en dietas, entrega de charolas y recolección, valoración nutricional del paciente hospitalizado.',
 17,
'[
  {"id":"nu-01","type":"riesgo","description":"Omisión de alergias o enfermedades relevantes que pueden desencadenar reacciones adversas graves (PR-NU-04)","cause":"Indicación médica incompleta, falta de comunicación entre el médico y el servicio de nutrición","effect":"Reacción alérgica grave, broncoaspiración, complicaciones en el paciente","probability":2,"impact":5,"action_plan":"Evaluación nutricional y preguntas por parte del personal de dietas. Revisión de indicación médica antes de preparar la dieta.","responsible":"Jefe de Nutrición","due_date":"2025-11-30","status":"en_control"},
  {"id":"nu-02","type":"riesgo","description":"Consistencia inadecuada de los alimentos que puede generar disfagia o broncoaspiración (PR-NU-04)","cause":"Error en la preparación de la dieta, falta de comunicación de la consistencia indicada","effect":"Broncoaspiración, neumonía por aspiración, riesgo de muerte","probability":2,"impact":3,"action_plan":"Verificación de la consistencia indicada en la dieta antes de la entrega. Capacitación del personal de cocina.","responsible":"Jefe de Nutrición","due_date":"2025-11-30","status":"en_control"},
  {"id":"nu-03","type":"riesgo","description":"Interacciones fármaco-nutrientes no identificadas (PR-NU-04)","cause":"Falta de comunicación entre farmacia, médico y nutrición","effect":"Reducción de la eficacia del medicamento o aumento de efectos adversos","probability":2,"impact":3,"action_plan":"Revisión de las interacciones fármaco-nutrientes al momento de indicar la dieta. Coordinación entre farmacia y nutrición.","responsible":"Jefe de Nutrición","due_date":"2025-12-31","status":"identificado"},
  {"id":"nu-04","type":"riesgo","description":"Contaminación cruzada entre pacientes en la entrega de dietas (PR-NU-13)","cause":"Manejo inadecuado de charolas y alimentos, falta de higiene en la distribución","effect":"Transmisión de enfermedades infecciosas entre pacientes","probability":2,"impact":4,"action_plan":"Lavado de manos constante y adecuado. Limpieza y desinfección del área de trabajo e instrumentos. Uso correcto y adecuado del equipo de protección.","responsible":"Jefe de Nutrición","due_date":"2025-11-30","status":"en_control"},
  {"id":"nu-05","type":"riesgo","description":"Malnutrición hospitalaria no identificada ni tratada oportunamente (PR-NU-14)","cause":"Falta de valoración nutricional al ingreso y seguimiento durante la estancia","effect":"Inmunocompromiso, mayor tiempo de estancia intrahospitalaria, aumento del tiempo de recuperación","probability":3,"impact":4,"action_plan":"Realizar el proceso de valoración nutricional de manera óptima y adecuada. Seguimiento continuo del estado nutricional del paciente.","responsible":"Jefe de Nutrición","due_date":"2025-11-30","status":"en_control"},
  {"id":"nu-06","type":"riesgo","description":"Desabasto de alimentos para pacientes (PR-NU-01)","cause":"Falta de requisición semanal oportuna de productos","effect":"Imposibilidad de cumplir con las dietas indicadas, insatisfacción del paciente","probability":2,"impact":3,"action_plan":"Requisición semanal de producto de manera oportuna.","responsible":"Jefe de Nutrición","due_date":"2025-12-31","status":"en_control"}
]'),

-- ── 2c. Facturación y Prestaciones Externas (IPEJAL) ─────────────
('Facturación y Prestaciones Externas (IPEJAL)', 'apoyo',
 'Jefe de Facturación / Coordinador IPEJAL',
 'Recepción de documentos y cobro de servicios a pacientes IPEJAL, programación de estudios para derechohabientes, control de ocupación hospitalaria y apego al contrato y tabuladores IPEJAL.',
 18,
'[
  {"id":"pe-01","type":"riesgo","description":"Omisión de cobros, servicios o insumos en la facturación de pacientes IPEJAL (PR-PE-01/02)","cause":"Falta de conocimiento o descuido en el registro de los servicios prestados","effect":"Pérdida de ingresos para el hospital, incumplimiento del contrato","probability":3,"impact":4,"action_plan":"Revisión de los documentos para cotejar los cobros establecidos. Revisión diaria del correo institucional.","responsible":"Jefe de Facturación","due_date":"2025-11-30","status":"en_control"},
  {"id":"pe-02","type":"riesgo","description":"No cobrar lo pactado en el contrato con IPEJAL (PR-PE-01/02)","cause":"Desconocimiento de los tabuladores vigentes, falta de actualización del personal","effect":"Pérdida de ingresos, incumplimiento contractual, posibles sanciones","probability":2,"impact":4,"action_plan":"Apego a los tabuladores establecidos en el contrato con IPEJAL.","responsible":"Jefe de Facturación","due_date":"2025-11-30","status":"en_control"},
  {"id":"pe-03","type":"riesgo","description":"Atraso en los cobros de servicios prestados a pacientes IPEJAL (PR-PE-01/02)","cause":"Demora en la entrega de documentación requerida, falta de organización","effect":"Retraso en la recuperación de ingresos, afectación al flujo de caja","probability":3,"impact":3,"action_plan":"Entrega de la documentación en tiempo y forma.","responsible":"Jefe de Facturación","due_date":"2025-11-30","status":"en_control"},
  {"id":"pe-04","type":"riesgo","description":"Desconocimiento de la ocupación hospitalaria para pacientes IPEJAL (PR-PE-01/02)","cause":"Falta de verificación diaria del censo hospitalario","effect":"Cobros incorrectos, omisión de servicios, diferencias en la facturación","probability":2,"impact":3,"action_plan":"Verificación del censo diario.","responsible":"Jefe de Facturación","due_date":"2025-11-30","status":"en_control"},
  {"id":"pe-05","type":"riesgo","description":"Omisión de lineamientos estipulados en el contrato con IPEJAL (PR-PE-01/02)","cause":"Desconocimiento o actualización tardía de los lineamientos contractuales","effect":"Incumplimiento del contrato, posibles sanciones o rescisión","probability":2,"impact":3,"action_plan":"Actuar conforme a los lineamientos estipulados en el contrato con IPEJAL.","responsible":"Jefe de Facturación","due_date":"2025-11-30","status":"en_control"}
]'),

-- ── 2d. Rehabilitación ────────────────────────────────────────────
('Rehabilitación', 'misional',
 'Jefe de Rehabilitación',
 'Atención de rehabilitación física: electroterapia, mecanoterapia, terapia ocupacional e hidroterapia.',
 19,
'[
  {"id":"re-01","type":"riesgo","description":"Tratamiento aplicado a paciente incorrecto en cualquier modalidad de rehabilitación (PR-RE-01/02/03/04)","cause":"Falta de verificación de la identidad del paciente antes del tratamiento","effect":"Tratamiento inapropiado, daño al paciente, evento adverso","probability":2,"impact":4,"action_plan":"Identificación correcta del paciente por medio de Nombre, Edad y Fecha de Nacimiento antes de cada procedimiento.","responsible":"Jefe de Rehabilitación","due_date":"2025-11-30","status":"en_control"},
  {"id":"re-02","type":"riesgo","description":"Tratamiento incorrecto por falta de verificación de indicaciones médicas (PR-RE-01/02/03/04)","cause":"No verificar las indicaciones y tratamientos prescritos por el médico","effect":"Daño al paciente, mala evolución clínica","probability":2,"impact":4,"action_plan":"Verificación de indicaciones y tratamientos antes de cada sesión.","responsible":"Jefe de Rehabilitación","due_date":"2025-11-30","status":"en_control"},
  {"id":"re-03","type":"riesgo","description":"Quemaduras al paciente por tipo de corrientes en electroterapia (PR-RE-01)","cause":"Revisión constante insuficiente en la aplicación de electroestímulos","effect":"Quemaduras superficiales o profundas, daño al paciente","probability":2,"impact":4,"action_plan":"Revisión constante en aplicación de electroestímulos. Nivelar la frecuencia del electroestimulador evitando que llegue a niveles altos.","responsible":"Jefe de Rehabilitación","due_date":"2025-11-30","status":"en_control"},
  {"id":"re-04","type":"riesgo","description":"Lesiones por mala ejecución del ejercicio en mecanoterapia (PR-RE-02)","cause":"Técnica incorrecta en la ejecución de los ejercicios","effect":"Lesiones musculoesqueléticas del paciente","probability":2,"impact":3,"action_plan":"Revisión constante durante la realización de los ejercicios. Enseñanza al paciente y familiares sobre la manera correcta de realizar los ejercicios en casa.","responsible":"Jefe de Rehabilitación","due_date":"2025-11-30","status":"en_control"},
  {"id":"re-05","type":"riesgo","description":"Caídas de pacientes por piso mojado en hidroterapia (PR-RE-04)","cause":"Falta de señalamiento y franjas antiderrapantes en el área de hidroterapia","effect":"Caídas con lesiones, prolongación de la estancia, responsabilidad legal","probability":3,"impact":3,"action_plan":"Evitar riesgo de caídas utilizando franjas antiderrapantes y señalamientos de piso mojado.","responsible":"Jefe de Rehabilitación","due_date":"2025-11-15","status":"en_control"},
  {"id":"re-06","type":"riesgo","description":"Olvidar pacientes en las tinas durante el tratamiento de hidroterapia (PR-RE-04)","cause":"Falta de vigilancia constante durante el tratamiento","effect":"Riesgo de ahogamiento, hipotermia o quemaduras, evento adverso grave","probability":1,"impact":5,"action_plan":"Vigilancia constante al tiempo de la ejecución del tratamiento muscular. No dejar sin supervisión a los pacientes en las tinas.","responsible":"Jefe de Rehabilitación","due_date":"2025-11-15","status":"en_control"},
  {"id":"re-07","type":"riesgo","description":"Actividades de terapia ocupacional realizadas de manera incorrecta (PR-RE-03)","cause":"Falta de capacitación o supervisión en las actividades asignadas","effect":"Mala evolución del paciente, frustración, posible lesión","probability":2,"impact":3,"action_plan":"Monitoreo de las actividades asignadas enseñando a los pacientes y familiares.","responsible":"Jefe de Rehabilitación","due_date":"2025-12-31","status":"en_control"}
]'),

-- ── 2e. Lavandería y Ropería ──────────────────────────────────────
('Lavandería y Ropería', 'apoyo',
 'Jefe de Servicios Generales / Empresa Subrogada',
 'Recepción, almacenamiento, distribución, manejo y disposición final de ropa hospitalaria (limpia y sucia). Proceso subrogado a empresa externa.',
 20,
'[
  {"id":"ro-01","type":"riesgo","description":"Riesgo de infecciones al paciente y al personal que manipula la ropa hospitalaria (PR-UV-21)","cause":"Manejo inadecuado de la ropa, falta de supervisión y comunicación entre los departamentos involucrados","effect":"Transmisión de enfermedades infecciosas, IAAS","probability":3,"impact":4,"action_plan":"Supervisión y comunicación continua por parte de los departamentos involucrados.","responsible":"Jefe de Servicios Generales","due_date":"2025-11-30","status":"en_control"},
  {"id":"ro-02","type":"riesgo","description":"Desconocimiento u omisión de los procesos e instrucciones relacionados con el manejo de ropa (PR-UV-21)","cause":"Falta de capacitación del personal en los procedimientos de manejo de ropa","effect":"Manejo incorrecto, riesgo de contaminación cruzada","probability":3,"impact":3,"action_plan":"Realizar capacitación de los procesos e instrucciones que deben aplicarse.","responsible":"Jefe de Servicios Generales","due_date":"2025-12-31","status":"identificado"},
  {"id":"ro-03","type":"riesgo","description":"Desabasto de stocks de ropa limpia en las distintas áreas (PR-RO-02)","cause":"Falta de coordinación con la empresa subrogada para la recepción en horarios establecidos","effect":"Áreas sin ropa limpia disponible, interrupción de la atención","probability":3,"impact":3,"action_plan":"Coordinación con la empresa subrogada para la recepción de ropa limpia en horarios establecidos.","responsible":"Jefe de Servicios Generales","due_date":"2025-12-31","status":"en_control"},
  {"id":"ro-04","type":"riesgo","description":"Pérdida monetaria por extravío de ropa limpia (PR-RO-02)","cause":"Falta de control de inventario y bitácoras de entrega/recepción","effect":"Pérdida económica para el hospital, desabasto en el mediano plazo","probability":2,"impact":3,"action_plan":"Control de bitácoras y realización de inventarios periódicos.","responsible":"Jefe de Servicios Generales","due_date":"2025-12-31","status":"identificado"}
]'),

-- ── 2f. Banco de Sangre ───────────────────────────────────────────
('Banco de Sangre', 'misional',
 'Jefe de Banco de Sangre',
 'Instrucciones de trabajo de hemoclasificación, determinación de subgrupos, rastreo e identificación de anticuerpos irregulares, pruebas de compatibilidad, control de calidad de hemocomponentes y determinación de autocontrol.',
 21,
'[
  {"id":"bs-01","type":"riesgo","description":"Confusión de tubos de ensayo o pocillos en pruebas de compatibilidad mayor/menor (IT-BS-14/15)","cause":"Falta de rotulado previo de los tubos y pocillos antes del uso","effect":"Transfusión incompatible, reacción transfusional grave, riesgo de muerte","probability":2,"impact":5,"action_plan":"Rotulado previo de tubos y pocillos antes del uso en todas las pruebas. Doble verificación antes de la transfusión.","responsible":"Jefe de Banco de Sangre","due_date":"2025-11-15","status":"en_control"},
  {"id":"bs-02","type":"riesgo","description":"Contaminación biológico-infecciosa del operario durante cualquier procedimiento de Banco de Sangre (IT-BS-08/10/11/14/15/18)","cause":"No uso de guantes y EPP durante las instrucciones de trabajo","effect":"Accidente biológico, transmisión de enfermedades infecciosas al operario","probability":2,"impact":4,"action_plan":"Uso obligatorio de guantes y EPP durante todas las instrucciones de trabajo de Banco de Sangre.","responsible":"Jefe de Banco de Sangre","due_date":"2025-11-15","status":"en_control"},
  {"id":"bs-03","type":"riesgo","description":"Lectura errónea de los patrones de aglutinación (IT-BS-08/10/11/14/15/18)","cause":"Iluminación insuficiente, falta de imagen de referencia en el área de lectura","effect":"Clasificación incorrecta de grupo sanguíneo o anticuerpos, error diagnóstico con consecuencias graves","probability":2,"impact":5,"action_plan":"Imagen de referencia en el área de inmuno-hematología y luz clara para la lectura. Buena iluminación en el área de lectura.","responsible":"Jefe de Banco de Sangre","due_date":"2025-11-15","status":"en_control"},
  {"id":"bs-04","type":"riesgo","description":"Envío de muestras erróneas al laboratorio de referencia (IT-BS-17)","cause":"Falta de rotulado de muestras antes del envío","effect":"Pérdida de muestra, resultados incorrectos, retraso diagnóstico","probability":2,"impact":4,"action_plan":"Rotulado de muestras antes del envío. Doble verificación de la identidad de la muestra.","responsible":"Jefe de Banco de Sangre","due_date":"2025-11-30","status":"en_control"},
  {"id":"bs-05","type":"riesgo","description":"Degradación de factores de coagulación por transporte prolongado de hemocomponentes (IT-BS-17)","cause":"Falta de envío oportuno por el chofer hospitalario en hora y día programado","effect":"Hemocomponente inútil, pérdida de material biológico valioso, costo elevado","probability":2,"impact":4,"action_plan":"Envío oportuno por el chofer hospitalario en hora y día programado. Uso de alícuotas acelulares para evitar sesgos.","responsible":"Jefe de Banco de Sangre","due_date":"2025-11-30","status":"en_control"},
  {"id":"bs-06","type":"riesgo","description":"Confusión de tubos de ensayo en determinación de subgrupos A (IT-BS-08)","cause":"Falta de rotulado de tubos de ensayo previo al uso","effect":"Determinación incorrecta de subgrupo sanguíneo, error transfusional","probability":2,"impact":4,"action_plan":"Rotulado de tubos de ensayo previo al uso de los mismos.","responsible":"Jefe de Banco de Sangre","due_date":"2025-11-30","status":"en_control"}
]'),

-- ── 2g. Seguridad Hospitalaria ────────────────────────────────────
('Seguridad Hospitalaria', 'apoyo',
 'Jefe de Seguridad',
 'Control de acceso a instalaciones, atención a personas violentas, control de ingreso y egreso del personal, acceso de proveedores y representantes comerciales, traslado de pacientes y visitantes.',
 22,
'[
  {"id":"sg-s01","type":"riesgo","description":"Afectación a terceras personas o al inmueble por la presencia de una persona violenta (PR-SG-01)","cause":"Acceso de personas con comportamiento agresivo a las instalaciones del hospital","effect":"Lesiones al personal, pacientes o visitantes, daño a la infraestructura","probability":2,"impact":4,"action_plan":"Rondines de vigilancia por parte del equipo de seguridad. Protocolo de atención a personas violentas.","responsible":"Jefe de Seguridad","due_date":"2025-11-30","status":"en_control"},
  {"id":"sg-s02","type":"riesgo","description":"Personas externas que atenten contra la seguridad de pacientes o personal (PR-SG-02)","cause":"Falta de control de acceso a proveedores, servicios externos y representantes comerciales","effect":"Robo, agresiones, daño a pacientes o personal","probability":2,"impact":4,"action_plan":"Registro de toda persona externa en la Bitácora de Control de Ingreso. Identificación a toda persona que ingrese.","responsible":"Jefe de Seguridad","due_date":"2025-11-30","status":"en_control"},
  {"id":"sg-s03","type":"riesgo","description":"Filtración de personas ajenas al hospital a áreas restringidas (PR-SG-02/23)","cause":"Control de acceso insuficiente o momentos de alta afluencia","effect":"Riesgo de seguridad para pacientes y personal, robo de información o materiales","probability":3,"impact":3,"action_plan":"Filtración de personas ajenas al hospital. Identificación a toda persona que ingrese. Llevar un control de accesos.","responsible":"Jefe de Seguridad","due_date":"2025-11-30","status":"en_control"},
  {"id":"sg-s04","type":"riesgo","description":"Robo de información, altercados o asaltos por personas ajenas al hospital (PR-SG-03)","cause":"Control de acceso insuficiente, falta de supervisión de portación de gafete","effect":"Pérdida de información sensible, daño económico, riesgo para el personal","probability":2,"impact":4,"action_plan":"Supervisión por parte de seguridad de la portación de gafete de todo el personal. Revisión de bolsos o mochilas al término de la jornada laboral.","responsible":"Jefe de Seguridad","due_date":"2025-12-31","status":"identificado"},
  {"id":"sg-s05","type":"riesgo","description":"Conflictos familiares, desorden o molestias a terceros durante visitas a habitaciones (PR-SG-23)","cause":"Incumplimiento del reglamento de visitas por pacientes, familiares o acompañantes","effect":"Ambiente de tensión, molestias a otros pacientes, necesidad de intervención del personal","probability":2,"impact":2,"action_plan":"Reglamento para pacientes, familiares y/o acompañantes. Realización de rondines de vigilancia.","responsible":"Jefe de Seguridad","due_date":"2025-12-31","status":"en_control"}
]')

ON CONFLICT DO NOTHING;


-- ══════════════════════════════════════════════════════════════════
-- SECCIÓN 3: VERIFICACIÓN FINAL
-- ══════════════════════════════════════════════════════════════════

SELECT
  name,
  process_type,
  process_owner,
  jsonb_array_length(risks) AS total_riesgos,
  sort_order
FROM risk_processes
ORDER BY sort_order, name;
